port=16667
plugin_dir=/usr/local/lib/imspector
user=_imspector
group=_imspector
icq_protocol=on
irc_protocol=on
msn_protocol=on
yahoo_protocol=on
gg_protocol=on
jabber_protocol=on
file_logging_dir=/var/www/htdocs/tn/data/logs/imspector
