languagedir = '/usr/local/share/e2guardian/languages'
language = 'ukenglish'
loglevel = 3
logexceptionhits = 2
logfileformat = 1
logsyslog = off
logfile = /var/www/htdocs/tn/data/logs/e2guardian/e2guardian.log
loglocation = '/var/www/htdocs/tn/data/logs/e2guardian/access.log'
filterip = 127.0.0.1
#filterip = ::1
filterports = 8080
mapportstoips = off
proxytimeout = 5
connecttimeout = 5
proxyexchange = 61
pcontimeout = 55
usecustombannedimage = on
custombannedimagefile = '/var/www/htdocs/tn/data/run/e2guardian/transparent1x1.gif'
usecustombannedflash = on
custombannedflashfile = '/var/www/htdocs/tn/data/run/e2guardian/blockedflash.swf'
filtergroups = 1
filtergroupslist = '/etc/e2guardian/lists/filtergroupslist'
iplist = 'name=bannedclient,messageno=100,logmessageno=103,path=/etc/e2guardian/lists/bannediplist'
iplist = 'name=exceptionclient,messageno=600,path=/etc/e2guardian/lists/exceptioniplist'
iplist = 'name=authexception,messageno=602,path=/etc/e2guardian/lists/authexceptioniplist'
sitelist = 'name=authexception,messageno=602,path=/etc/e2guardian/lists/authexceptionsitelist'
urllist = 'name=authexception,messageno=603,path=/etc/e2guardian/lists/authexceptionurllist'
showweightedfound = on
weightedphrasemode = 2
phrasefiltermode = 2
preservecase = 0
hexdecodecontent = off
forcequicksearch = off
reverseaddresslookups = off
reverseclientiplookups = off
logclienthostnames = off
maxcontentfiltersize = 2048
maxcontentramcachescansize = 10240
maxcontentfilecachescansize = 20000
filecachedir = '/var/www/htdocs/tn/data/tmp/e2guardian'
deletedownloadedtempfiles = on
initialtrickledelay = 20
trickledelay = 10
downloadmanager = '/etc/e2guardian/downloadmanagers/default.conf'
contentscanner = '/etc/e2guardian/contentscanners/clamdscan.conf'
contentscannertimeout = 60
authplugin = '/etc/e2guardian/authplugins/ip.conf'
recheckreplacedurls = off
forwardedfor = off
usexforwardedfor = off
logconnectionhandlingerrors = on
httpworkers = 50
pidfilename = '/var/www/htdocs/tn/data/run/e2guardian/e2guardian.pid'
nodaemon = off
nologger = off
logadblocks = on
loguseragent = off
daemonuser = '_e2guardian'
daemongroup = '_e2guardian'
enablessl = off
preauthstoryboard = '/etc/e2guardian/preauth.story'
searchsitelistforip = on
maxheaderlines = 100
