#!/bin/ksh

# SPDX-FileCopyrightText: 2026 David Peter, Tangent Networks
#
# SPDX-License-Identifier: BSD-3-Clause

# =============================================================================
# TN_UTM_UNINSTALLER.sh -- Tangent Networks UTM Uninstaller
# =============================================================================
#
# AUTHOR:   Tangent Networks
# VERSION:  1.2.0
# PLATFORM: OpenBSD (pdksh / /bin/ksh)
#
# PURPOSE:
#   Removes the Tangent Networks UTM installation from this machine in a
#   controlled, step-by-step sequence. Each step is gated by the sentinel
#   file written by the script that owns it -- if a script did not complete
#   successfully its corresponding uninstall step is skipped entirely.
#   This makes the uninstaller safe for partial installs and for installs
#   where individual scripts were run independently rather than via the
#   master orchestrator TN_UTM_INSTALLER.sh.
#
# USAGE:
#   doas ksh TN_UTM_UNINSTALLER.sh
#
#   Must be run as root from the installer directory (the same directory
#   that contains the four installer scripts and net-backup/).
#
# SENTINEL GATES:
#   Each uninstall step is gated by the sentinel written by its installer:
#
#   /etc/tn-network-setup.status  (TN_NET_SET.sh)
#     Gates: Step 7  -- restore system config files from net-backup/
#            Step 8  -- remove SSL certificates and CA
#
#   /root/packages-setup  (TN_PKG_INSTALL.sh)
#     Gates: Step 1  -- stop and disable services
#            Step 2  -- remove packages
#            Step 3  -- remove /usr/local/sbin files
#            Step 4  -- remove webroot
#            Step 5  -- remove AuthDB and session keys
#
#   ~/chroot-setup  (TN_CHROOT_SETUP.sh)
#     Gates: Step 6  -- remove chroot additions
#
#   Steps 9 and 10 are not gated -- always safe to run.
#
# NET-BACKUP COVERAGE:
#   TN_NET_SET.sh backs up:
#     /etc/myname, /etc/mygate, /etc/resolv.conf, /etc/rc,
#     /etc/rc.conf.local, /etc/sysctl.conf, /etc/syslog.conf,
#     /etc/newsyslog.conf, /etc/crontab, /etc/pf.conf,
#     /etc/hostname.*
#
#   TN_PKG_INSTALL.sh backs up (if present before install):
#     /etc/rc.local
#
#   Files absent from net-backup/ were not present before install.
#   The uninstaller truncates rather than restores those files.
#
# NULLFS NOTE:
#   If TN_CHROOT_SETUP.sh was skipped and nullfs was mounted instead,
#   ~/chroot-setup will be absent and Step 6 is skipped automatically.
#   Unmount any nullfs mounts manually before running this script:
#     mount | grep nullfs
#
# WHAT THIS SCRIPT DOES NOT DO:
#   - Does not reboot. A reboot is required after Step 7.
#   - Does not remove the installer directory itself.
#   - Does not remove OpenBSD base system packages or system users
#     created by pkg_add (_snort, _e2guardian, etc.).
#   - Does not touch /var/www/ base chroot outside chroot-manifest.txt.
#   - Does not unmount nullfs mounts.
#
# =============================================================================

TN_INSTALL_DATE="UNSTAMPED" # replaced by TN_UTM_INSTALLER.sh at install time

# =============================================================================
# SHELL OPTIONS
# =============================================================================
set -u

# =============================================================================
# PATHS
# =============================================================================
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Webroot
BASE="/var/www/htdocs/tn/data"
WEBROOT="/var/www/htdocs/tn"

# Pre-install backup directory written by TN_NET_SET.sh and TN_PKG_INSTALL.sh
NET_BACKUP="${SCRIPT_DIR}/net-backup"

# Chroot manifest written by TN_CHROOT_SETUP.sh
MANIFEST="${SCRIPT_DIR}/chroot-manifest.txt"

# Sbin manifest written by TN_PKG_INSTALL.sh
SBIN_MANIFEST="${SCRIPT_DIR}/rollback/sbin-manifest.txt"

# Installer log directory
LOG_DIR="${SCRIPT_DIR}/logs"
UNINSTALL_LOG="${LOG_DIR}/uninstall_$(date +%Y%m%d_%H%M%S).log"

# =============================================================================
# SENTINELS -- written by each installer script on successful completion
# =============================================================================
SENTINEL_NET="/etc/tn-network-setup.status"  # TN_NET_SET.sh
SENTINEL_PKG="/root/packages-setup"          # TN_PKG_INSTALL.sh
SENTINEL_CHROOT="${HOME}/chroot-setup"       # TN_CHROOT_SETUP.sh
SENTINEL_INSTALL_DATE="/etc/tn-install-date" # TN_CHROOT_SETUP.sh
PHASE_STATE="${SCRIPT_DIR}/.install_phases"  # TN_PKG_INSTALL.sh
TN_INTERFACES="/etc/tn-interfaces"           # TN_NET_SET.sh

# AuthDB and keys
AUTH_DB="${BASE}/db/auth.db"
SESSION_KEY="${BASE}/run/session/session.key"
HMAC_KEY="${BASE}/run/session/hmac.key"

# SSL -- generated by TN_NET_SET.sh
SSL_DIR="/etc/ssl"
SSL_PRIVATE_DIR="/etc/ssl/private"
TN_CA_CERT="${SSL_DIR}/tn-ca.crt"
TN_CA_SERIAL="${SSL_DIR}/tn-ca.serial"

# Services -- must match TN_PKG_INSTALL.sh definitions exactly
RCD_SERVICES="cron dhcpd ftpproxy ftpproxy6 httpd ntpd rad slaacd slowcgi smtpd syslogd unbound"
LOCAL_SERVICES="snort snortinline snortsentry e2guardian collectd p3scan clamd freshclam \
pmacct sockd spamd smtp-gated sslproxy imspector tcpdump"

# Packages -- must match TN_PKG_INSTALL.sh definitions exactly
MIRROR_PKGS="curl base64 bzip2 clamav collectd collectd-ping collectd-rrdtool dante daq drill \
iso-codes jq libb2 libdnet libevent libffi libiconv libltdl libnet liboping libpaper libsigsegv \
libstatgrab libtool libyajl lunzip oinkmaster p5-Crypt-PBKDF2 p5-Crypt-SSLeay p5-DateManip \
p5-DateTime p5-Digest-SHA3 p5-File-Scan-ClamAV p5-File-Slurp p5-File-Slurp-Tiny p5-File-Which \
p5-HTML-Lint p5-IO-Socket-Timeout p5-IPC-Run p5-JSON p5-JSON-XS p5-LWP-Protocol-https \
p5-MIME-Lite p5-MIME-Types p5-Mail-SpamAssassin p5-Net-IP p5-Net-SMTP-SSL p5-Readonly \
p5-Sys-Hostname-Long p5-Text-Markdown p5-XML-Parser p5-libwww pcre rrdtool socat sqlite3 \
truncate wget xz zip p5-DBD-SQLite2"

VERSION_PKGS="db python"
UNFLAVORED_PKGS="pmacct unzip"
CUSTOM_PKGS="SSLproxy e2guardian imspector p3scan smtp-gated snort snortsentry"

# =============================================================================
# COLOURS
# =============================================================================
if [ -t 1 ]; then
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  CYAN='\033[0;36m'
  BOLD='\033[1m'
  MAGENTA='\033[0;35m'
  NC='\033[0m'
else
  RED=''
  GREEN=''
  YELLOW=''
  CYAN=''
  BOLD=''
  MAGENTA=''
  NC=''
fi

# =============================================================================
# LOGGING
# =============================================================================
mkdir -p "$LOG_DIR"

log() { printf "[%s] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$*" | tee -a "$UNINSTALL_LOG"; }
ok() { printf "  ${GREEN}[OK]${NC}    %s\n" "$*" | tee -a "$UNINSTALL_LOG"; }
info() { printf "  ${CYAN}[INFO]${NC}  %s\n" "$*" | tee -a "$UNINSTALL_LOG"; }
warn() { printf "  ${YELLOW}[WARN]${NC}  %s\n" "$*" | tee -a "$UNINSTALL_LOG"; }
err() { printf "  ${RED}[ERR]${NC}   %s\n" "$*" | tee -a "$UNINSTALL_LOG"; }
die() {
  err "$*"
  log "ABORT: $*"
  exit 1
}

print_header() {
  echo ""
  echo "============================================================"
  printf "  ${BOLD}%s${NC}\n" "$1"
  echo "============================================================"
  log "=== $1 ==="
}

# =============================================================================
# OPERATOR CONFIRMATION
# y   -- proceed with this step
# n   -- skip this step, continue to the next
# q   -- quit immediately, no further steps executed
# =============================================================================
confirm() {
  printf "\n  ${MAGENTA}%s${NC}\n" "$1"
  printf "  ${MAGENTA}Proceed? [y/N/q]: ${NC}"
  read _cf_ans_
  case "$_cf_ans_" in
    [Yy]*)
      log "CONFIRMED: $1"
      return 0
      ;;
    [Qq]*)
      log "QUIT at: $1"
      printf "\n  Uninstall stopped by operator. No further changes.\n\n"
      exit 0
      ;;
    *)
      log "SKIPPED: $1"
      warn "Skipped."
      return 1
      ;;
  esac
}

# =============================================================================
# PRE-FLIGHT
# =============================================================================
print_header "TN_UTM_UNINSTALLER v1.2.0"
log "Uninstall log: ${UNINSTALL_LOG}"

[ "$(id -u)" -ne 0 ] && die "Must run as root: doas ksh $0"
[ "$(uname -s)" != "OpenBSD" ] && die "OpenBSD only"

# =============================================================================
# INSTALL DATE RESOLUTION
# Resolved in order: stamped variable -> /etc/tn-install-date ->
# date line in network sentinel -> unknown.
# Used only for informational purposes -- all steps are sentinel-gated.
# =============================================================================
if [ "$TN_INSTALL_DATE" = "UNSTAMPED" ]; then
  if [ -f "$SENTINEL_INSTALL_DATE" ]; then
    . "$SENTINEL_INSTALL_DATE"
    info "Install date from /etc/tn-install-date: ${TN_INSTALL_DATE}"
  elif [ -f "$SENTINEL_NET" ]; then
    TN_INSTALL_DATE=$(head -1 "$SENTINEL_NET" 2> /dev/null \
      | grep -oE '[0-9]{8}-[0-9]{6}' || true)
    if [ -n "$TN_INSTALL_DATE" ]; then
      info "Install date derived from network sentinel: ${TN_INSTALL_DATE}"
    else
      TN_INSTALL_DATE="unknown"
      warn "Cannot determine install date from sentinel"
    fi
  else
    TN_INSTALL_DATE="unknown"
    warn "No install date source found"
  fi
fi

# =============================================================================
# INSTALLATION STATUS SUMMARY
# Shows operator exactly what completed and what steps will be skipped.
# =============================================================================
print_header "Installation Status"

if [ -f "$SENTINEL_NET" ]; then
  ok "TN_NET_SET.sh:      complete  (${SENTINEL_NET})"
else
  warn "TN_NET_SET.sh:      sentinel not found -- Steps 7 and 8 will be skipped"
fi

if [ -f "$SENTINEL_PKG" ]; then
  ok "TN_PKG_INSTALL.sh:  complete  (${SENTINEL_PKG})"
else
  warn "TN_PKG_INSTALL.sh:  sentinel not found -- Steps 1-5 will be skipped"
fi

if [ -f "$SENTINEL_CHROOT" ]; then
  ok "TN_CHROOT_SETUP.sh: complete  (${SENTINEL_CHROOT})"
else
  warn "TN_CHROOT_SETUP.sh: sentinel not found -- Step 6 will be skipped"
  warn "                    If nullfs was used, unmount manually first."
  warn "                    Check: mount | grep nullfs"
fi

echo ""
[ -d "$NET_BACKUP" ] && ok "net-backup/:          present" \
  || warn "net-backup/:          not found -- Step 7 restore skipped"
[ -f "$MANIFEST" ] && ok "chroot-manifest.txt:  present" \
  || warn "chroot-manifest.txt:  not found -- Step 6 removal skipped"
[ -f "$SBIN_MANIFEST" ] && ok "sbin-manifest.txt:    present" \
  || warn "sbin-manifest.txt:    not found -- Step 3 removal skipped"

info "Install date: ${TN_INSTALL_DATE}"

# =============================================================================
# MASTER CONFIRMATION
# =============================================================================
echo ""
printf "  ${BOLD}This will remove the Tangent Networks UTM installation.${NC}\n"
printf "  ${BOLD}Only completed stages will be uninstalled (sentinel-gated).${NC}\n"
printf "  ${BOLD}Each step will ask for confirmation before proceeding.${NC}\n"
printf "  ${BOLD}Type 'q' at any prompt to stop without further changes.${NC}\n"
printf "  ${BOLD}A reboot is required after completion.${NC}\n"
echo ""
printf "  ${MAGENTA}Type CONFIRM to begin: ${NC}"
read _master_confirm_
[ "$_master_confirm_" = "CONFIRM" ] || {
  info "Uninstall cancelled."
  exit 0
}
log "Master confirmation received."

# =============================================================================
# STEP 1 -- STOP AND DISABLE SERVICES
# Gated by: SENTINEL_PKG (/root/packages-setup)
# Uses service_manager.sh which handles ordering and dependencies correctly.
# rcctl disable is still run after to prevent services starting on reboot.
# =============================================================================
print_header "Step 1: Stop and Disable Services"
if [ ! -f "$SENTINEL_PKG" ]; then
  warn "TN_PKG_INSTALL.sh sentinel not found -- Step 1 skipped"
else
  _SVC_MGR="/usr/local/sbin/service_manager.sh"
  info "Services: ${LOCAL_SERVICES} ${RCD_SERVICES}"
  if confirm "Stop and disable all UTM services"; then
    if [ -x "$_SVC_MGR" ]; then
      info "Stopping all UTM services via service_manager.sh..."
      for _svc in $("$_SVC_MGR" list 2>/dev/null); do
        "$_SVC_MGR" stop "$_svc" 2>/dev/null && ok "Stopped: $_svc" \
          || warn "Could not stop: $_svc -- may already be down"
      done
      ok "All UTM services stopped."
    else
      warn "service_manager.sh not found -- services may still be running"
      warn "Manually stop services before proceeding if possible."
    fi
    # Disable rc.conf.local services via rcctl
    for _svc in $LOCAL_SERVICES $RCD_SERVICES; do
      rcctl disable "$_svc" 2>/dev/null || true
    done
    # Disable base rc services that UTM enables
    for _svc in cron dhcpd ftpproxy ftpproxy6 httpd rad slowcgi unbound; do
      rcctl disable "$_svc" 2>/dev/null && ok "Disabled: $_svc" || true
    done
    ok "All UTM services stopped and disabled."
  fi
fi

# =============================================================================
# STEP 2 -- REMOVE PACKAGES
# Gated by: SENTINEL_PKG (/root/packages-setup)
# Custom packages removed first -- they depend on mirror packages.
# Each package looked up live via pkg_info -- only installed ones acted on.
# =============================================================================
print_header "Step 2: Remove Installed Packages"

if [ ! -f "$SENTINEL_PKG" ]; then
  warn "TN_PKG_INSTALL.sh sentinel not found -- Step 2 skipped"
else
  info "Removes all packages installed by TN_PKG_INSTALL.sh."
  info "Dependencies shared with the base system will not be removed."

  if confirm "Remove all UTM packages via pkg_delete"; then
    for _pkg in $CUSTOM_PKGS; do
      _installed=$(pkg_info -q 2> /dev/null | grep -i "^${_pkg}" | head -1 || true)
      if [ -n "$_installed" ]; then
        pkg_delete -f "$_installed" 2> /dev/null \
          || warn "pkg_delete failed for $_installed -- may already be removed"
        ok "Removed: $_installed"
      else
        info "Not installed, skipping: $_pkg"
      fi
    done
    for _pkg in $UNFLAVORED_PKGS; do
      _installed=$(pkg_info -q 2> /dev/null | grep -i "^${_pkg}-" | head -1 || true)
      if [ -n "$_installed" ]; then
        pkg_delete -f "$_installed" 2> /dev/null || true
        ok "Removed: $_installed"
      else
        info "Not installed, skipping: $_pkg"
      fi
    done
    for _pkg in $VERSION_PKGS; do
      _installed=$(pkg_info -q 2> /dev/null | grep -i "^${_pkg}-[0-9]" | head -1 || true)
      if [ -n "$_installed" ]; then
        pkg_delete -f "$_installed" 2> /dev/null || true
        ok "Removed: $_installed"
      else
        info "Not installed, skipping: $_pkg"
      fi
    done
    for _pkg in $MIRROR_PKGS; do
      _installed=$(pkg_info -q 2> /dev/null | grep -i "^${_pkg}-" | head -1 || true)
      if [ -n "$_installed" ]; then
        pkg_delete -f "$_installed" 2> /dev/null || true
        ok "Removed: $_installed"
      else
        info "Not installed, skipping: $_pkg"
      fi
    done
    ok "Package removal complete."
  fi
fi

# =============================================================================
# STEP 3 -- REMOVE /usr/local/sbin FILES
# Gated by: SENTINEL_PKG (/root/packages-setup) and SBIN_MANIFEST
# Only files listed in sbin-manifest.txt are removed.
# =============================================================================
print_header "Step 3: Remove UTM sbin Files"

if [ ! -f "$SENTINEL_PKG" ]; then
  warn "TN_PKG_INSTALL.sh sentinel not found -- Step 3 skipped"
elif [ ! -f "$SBIN_MANIFEST" ]; then
  warn "sbin-manifest.txt not found at ${SBIN_MANIFEST} -- Step 3 skipped"
  info "Manually inspect /usr/local/sbin/ and remove TN files if needed."
else
  info "Sbin manifest: ${SBIN_MANIFEST}"
  info "Files to remove:"
  cat "$SBIN_MANIFEST" | sed 's/^/    /'

  if confirm "Remove all /usr/local/sbin/ files listed in sbin manifest"; then
    while IFS= read -r _sbinf; do
      [ -z "$_sbinf" ] && continue
      if [ -f "$_sbinf" ]; then
        rm -f "$_sbinf"
        ok "Removed: $_sbinf"
      else
        info "Already absent: $_sbinf"
      fi
    done < "$SBIN_MANIFEST"
    ok "sbin files removed."
  fi
fi

# =============================================================================
# STEP 4 -- REMOVE WEBROOT
# Gated by: SENTINEL_PKG (/root/packages-setup)
# /var/www/htdocs/tn/ is entirely our creation -- clean rm -rf.
# =============================================================================
print_header "Step 4: Remove Webroot"

if [ ! -f "$SENTINEL_PKG" ]; then
  warn "TN_PKG_INSTALL.sh sentinel not found -- Step 4 skipped"
else
  info "Removes: ${WEBROOT}"
  info "Entirely our creation -- no base system files live here."

  if confirm "Remove ${WEBROOT} entirely"; then
    if [ -d "$WEBROOT" ]; then
      rm -rf "$WEBROOT"
      ok "Removed: ${WEBROOT}"
    else
      info "Already absent: ${WEBROOT}"
    fi
  fi
fi

# =============================================================================
# STEP 5 -- REMOVE AUTHDB AND SESSION KEYS
# Gated by: SENTINEL_PKG (/root/packages-setup)
# All three files are entirely our creation -- clean delete.
# =============================================================================
print_header "Step 5: Remove AuthDB and Session Keys"

if [ ! -f "$SENTINEL_PKG" ]; then
  warn "TN_PKG_INSTALL.sh sentinel not found -- Step 5 skipped"
else
  info "Files to remove:"
  info "  ${AUTH_DB}"
  info "  ${SESSION_KEY}"
  info "  ${HMAC_KEY}"

  if confirm "Remove AuthDB, session key, and hmac key"; then
    for _kf in "$AUTH_DB" "$SESSION_KEY" "$HMAC_KEY"; do
      if [ -f "$_kf" ]; then
        rm -f "$_kf"
        ok "Removed: $_kf"
      else
        info "Already absent: $_kf"
      fi
    done
    ok "AuthDB and keys removed."
  fi
fi

# =============================================================================
# STEP 6 -- REMOVE CHROOT ADDITIONS
# Gated by: SENTINEL_CHROOT (~/chroot-setup) and MANIFEST
# Only files listed in chroot-manifest.txt are removed.
# Base OpenBSD /var/www/ chroot structure is untouched.
# If sentinel absent -- nullfs may have been used instead, skip entirely.
# =============================================================================
print_header "Step 6: Remove Chroot Additions"

if [ ! -f "$SENTINEL_CHROOT" ]; then
  warn "TN_CHROOT_SETUP.sh sentinel not found -- Step 6 skipped"
  warn "If nullfs was used instead of chroot, unmount manually."
  warn "Check: mount | grep nullfs"
elif [ ! -f "$MANIFEST" ]; then
  warn "chroot-manifest.txt not found at ${MANIFEST} -- Step 6 skipped"
  info "Manually inspect /var/www/usr/ and /var/www/lib/ for TN additions."
else
  _manifest_count=$(wc -l < "$MANIFEST" | tr -d ' ')
  info "Chroot manifest: ${MANIFEST} (${_manifest_count} entries)"
  info "Only manifest-listed files removed -- base chroot untouched."

  if confirm "Remove chroot additions listed in chroot-manifest.txt"; then
    while IFS= read -r _cf; do
      [ -z "$_cf" ] && continue
      _chroot_path="/var/www${_cf}"
      if [ -f "$_chroot_path" ]; then
        rm -f "$_chroot_path"
        ok "Removed: $_chroot_path"
      elif [ -d "$_chroot_path" ]; then
        rmdir "$_chroot_path" 2> /dev/null || true
      else
        info "Already absent: $_chroot_path"
      fi
    done < "$MANIFEST"
    ok "Chroot additions removed."
  fi
fi

# =============================================================================
# STEP 7 -- RESTORE SYSTEM CONFIG FILES
# Gated by: SENTINEL_NET or SENTINEL_PKG (either completing means net-backup/
# was written). Both TN_NET_SET.sh and TN_PKG_INSTALL.sh contribute to
# net-backup/ so either sentinel being present means restoration is valid.
#
# Restore strategy:
#   - Files present in net-backup/ are restored to /etc/ verbatim.
#   - /etc/rc.local absent from net-backup/ means it did not exist before
#     install -- truncate our copy rather than leave UTM entries running.
#   - /etc/crontab absent from net-backup/ means it did not exist before
#     install -- truncate our copy rather than leave UTM jobs scheduled.
#   - A reboot is required after this step.
# =============================================================================
print_header "Step 7: Restore System Config Files"

if [ ! -f "$SENTINEL_NET" ] && [ ! -f "$SENTINEL_PKG" ]; then
  warn "No installer sentinels found -- Step 7 skipped"
  warn "System config files were not backed up or install did not complete."
elif [ ! -d "$NET_BACKUP" ]; then
  warn "net-backup/ not found at ${NET_BACKUP} -- Step 7 skipped"
  warn "Manually restore /etc/hostname.*, /etc/mygate, /etc/pf.conf,"
  warn "/etc/rc, /etc/rc.conf.local, /etc/sysctl.conf from your own backups."
else
  info "Restoring from: ${NET_BACKUP}"
  info "Files to restore:"
  for _bak in "${NET_BACKUP}"/*; do
    [ -f "$_bak" ] || continue
    printf "    /etc/%s\n" "$(basename $_bak)"
  done
  [ ! -f "${NET_BACKUP}/rc.local" ] \
    && info "  /etc/rc.local not in net-backup/ -- will be truncated (did not exist before install)"
  [ ! -f "${NET_BACKUP}/crontab" ] \
    && info "  /etc/crontab not in net-backup/ -- will be truncated (did not exist before install)"
  warn "A reboot is required after this step for interface changes to take effect."

  if confirm "Restore all system config files from net-backup/"; then
    # Restore all files present in net-backup/
    for _bak in "${NET_BACKUP}"/*; do
      [ -f "$_bak" ] || continue
      _target="/etc/$(basename $_bak)"
      cp -p "$_bak" "$_target"
      ok "Restored: $_target"
    done

    # smtpd.conf lives in /etc/mail/ not /etc/
    if [ -f "${NET_BACKUP}/smtpd.conf" ]; then
      cp -p "${NET_BACKUP}/smtpd.conf" /etc/mail/smtpd.conf
      ok "Restored: /etc/mail/smtpd.conf"
    fi

    # /etc/rc.local -- truncate if it was not present before install.
    # Preserves the file in case something expects it to exist at boot
    # while removing all UTM content from it.
    if [ ! -f "${NET_BACKUP}/rc.local" ] && [ -f /etc/rc.local ]; then
      printf '' > /etc/rc.local
      ok "Truncated: /etc/rc.local (did not exist before install)"
    fi

    # /etc/crontab -- truncate if it was not present before install.
    # UTM jobs must not remain scheduled after removal.
    if [ ! -f "${NET_BACKUP}/crontab" ] && [ -f /etc/crontab ]; then
      printf '' > /etc/crontab
      ok "Truncated: /etc/crontab (did not exist before install)"
    fi

    if confirm "Restore all system config files from net-backup/"; then
      for _bak in "${NET_BACKUP}"/*; do
        [ -f "$_bak" ] || continue
        _target="/etc/$(basename $_bak)"
        cp -p "$_bak" "$_target"
        ok "Restored: $_target"
      done
      if [ ! -f "${NET_BACKUP}/rc.local" ] && [ -f /etc/rc.local ]; then
        printf '' > /etc/rc.local
        ok "Truncated: /etc/rc.local (did not exist before install)"
      fi
      if [ ! -f "${NET_BACKUP}/crontab" ] && [ -f /etc/crontab ]; then
        printf '' > /etc/crontab
        ok "Truncated: /etc/crontab (did not exist before install)"
      fi
      # fstab restored -- unmount orphaned TN MFS mounts
      info "Removing TN MFS mounts orphaned by fstab restore..."
      _mfs_mounts=$(mount | grep "mfs:.*on /var/www/htdocs/tn" | awk '{print $3}')
      if [ -n "$_mfs_mounts" ]; then
        echo "$_mfs_mounts" | while read -r _mnt; do
          fuser -ck "$_mnt" 2> /dev/null || true
          sleep 1
          fuser -ck -9 "$_mnt" 2> /dev/null || true
          if umount -f "$_mnt" 2> /dev/null; then
            ok "Unmounted orphaned MFS: $_mnt"
          else
            warn "Could not unmount: $_mnt -- will be released on reboot"
          fi
        done
      else
        info "No TN MFS mounts active."
      fi
      ok "System config files restored."
      warn "Reboot required -- hostname.* and mygate changes need a restart."
    fi
    ok "System config files restored."
    warn "Reboot required -- hostname.* and mygate changes need a restart."
  fi
fi

# =============================================================================
# STEP 8 -- REMOVE SSL CERTIFICATES AND CA
# Gated by: SENTINEL_NET (/etc/tn-network-setup.status)
# Runs before Step 9 which removes /etc/tn-interfaces (CERT_CN source).
# Remove tn-ca.crt from browsers/devices on your network after this step.
# =============================================================================
print_header "Step 8: Remove SSL Certificates and CA"

if [ ! -f "$SENTINEL_NET" ]; then
  warn "TN_NET_SET.sh sentinel not found -- Step 8 skipped"
else
  info "Removes TN CA and server certificate generated by TN_NET_SET.sh."
  info "  ${TN_CA_CERT}"
  info "  ${TN_CA_SERIAL}"

  # Read CERT_CN from tn-interfaces before Step 9 removes it
  _cert_cn=""
  [ -f "$TN_INTERFACES" ] \
    && _cert_cn=$(grep '^CERT_CN=' "$TN_INTERFACES" 2> /dev/null | cut -d'"' -f2)
  if [ -n "$_cert_cn" ]; then
    info "  ${SSL_DIR}/${_cert_cn}.crt"
    info "  ${SSL_PRIVATE_DIR}/${_cert_cn}.key"
  else
    warn "CERT_CN not found in tn-interfaces -- server cert path unknown"
    warn "Manually scan ${SSL_DIR}/ for tn-* files after this step."
  fi
  warn "Remove tn-ca.crt from any browsers or devices on your network."

  if confirm "Remove TN SSL certificates and CA"; then
    for _sf in "$TN_CA_CERT" "$TN_CA_SERIAL"; do
      [ -f "$_sf" ] && rm -f "$_sf" && ok "Removed: $_sf" \
        || info "Already absent: $_sf"
    done
    if [ -n "$_cert_cn" ]; then
      _srv_crt="${SSL_DIR}/${_cert_cn}.crt"
      _srv_key="${SSL_PRIVATE_DIR}/${_cert_cn}.key"
      [ -f "$_srv_crt" ] && rm -f "$_srv_crt" && ok "Removed: $_srv_crt" \
        || info "Already absent: $_srv_crt"
      [ -f "$_srv_key" ] && rm -f "$_srv_key" && ok "Removed: $_srv_key" \
        || info "Already absent: $_srv_key"
    fi
    # SSLproxy CA cert and key -- deployed by TN_PKG_INSTALL.sh STEP 3b
    for _sf in \
      /usr/local/etc/sslproxy/ca.crt \
      /usr/local/etc/sslproxy/ca.key; do
      [ -f "$_sf" ] && rm -f "$_sf" && ok "Removed: $_sf" \
        || info "Already absent: $_sf"
    done
    # Payload copies -- generated by TN_NET_SET.sh Stage 23b-i
    # Remove so reinstall generates fresh certs rather than reusing old ones
    for _sf in \
      "${SCRIPT_DIR}/payload/usr/local/etc/sslproxy/ca.crt" \
      "${SCRIPT_DIR}/payload/usr/local/etc/sslproxy/ca.key"; do
      [ -f "$_sf" ] && rm -f "$_sf" && ok "Removed payload copy: $_sf" \
        || info "Already absent: $_sf"
    done
    ok "SSL certificates removed."
  fi
fi

# =============================================================================
# STEP 9 -- REMOVE SENTINELS AND INVENTORY FILES
# Not gated -- always safe to remove regardless of install state.
# =============================================================================
print_header "Step 9: Remove Sentinels and Inventory Files"
info "Removes all installer state and inventory files:"
info "  ${SENTINEL_PKG}"
info "  ${SENTINEL_CHROOT}"
info "  ${SENTINEL_NET}"
info "  ${SENTINEL_INSTALL_DATE}"
info "  ${PHASE_STATE}"
info "  ${TN_INTERFACES}"

if confirm "Remove all installer sentinels and inventory files"; then
  for _sf in \
    "$SENTINEL_PKG" \
    "$SENTINEL_CHROOT" \
    "$SENTINEL_NET" \
    "$SENTINEL_INSTALL_DATE" \
    "$PHASE_STATE" \
    "$TN_INTERFACES"; do
    [ -f "$_sf" ] && rm -f "$_sf" && ok "Removed: $_sf" \
      || info "Already absent: $_sf"
  done
  ok "Sentinels and inventory removed."
fi

# =============================================================================
# STEP 10 -- REMOVE INSTALLER LOGS, ROLLBACK DIRECTORY, AND WEBROOT SAFEGUARD
# Not gated -- optional cleanup, always safe to skip.
# Copy the uninstall log elsewhere before confirming if you need a record.
# Webroot safeguard: removes /var/www/htdocs/tn if Step 4 was skipped or
# incomplete. MFS mounts are unmounted first; active log mounts (pf) that
# cannot be unmounted are left for manual removal after reboot.
# =============================================================================
print_header "Step 10: Remove Installer Logs, Rollback Directory, and Webroot Safeguard"
info "Removes: ${LOG_DIR}/"
info "         ${SCRIPT_DIR}/rollback/"
info "Safeguard: removes /var/www/htdocs/tn if still present."
warn "This removes all installer logs including this uninstall log."
warn "Copy ${UNINSTALL_LOG} elsewhere first if you need a permanent record."

if confirm "Remove installer logs, rollback directory, and any remaining webroot"; then
  if [ -d "${SCRIPT_DIR}/rollback" ]; then
    rm -rf "${SCRIPT_DIR}/rollback"
    ok "Removed: ${SCRIPT_DIR}/rollback/"
  else
    info "Already absent: ${SCRIPT_DIR}/rollback/"
  fi

  # Webroot safeguard -- catches surviving data/ if Step 4 was skipped
  if [ -d "/var/www/htdocs/tn" ]; then
    warn "/var/www/htdocs/tn still present -- running safeguard removal"

    # Unmount any mfs mounts, killing processes using them first
    _mfs_mounts=$(mount | grep "mfs:.*on /var/www/htdocs/tn" | awk '{print $3}')
    if [ -n "$_mfs_mounts" ]; then
      warn "MFS mounts detected -- killing users and unmounting"
      echo "$_mfs_mounts" | while read -r _mnt; do
        info "Processing: $_mnt"
        fuser -ck "$_mnt" 2> /dev/null || true
        sleep 1
        fuser -ck -9 "$_mnt" 2> /dev/null || true
        if umount "$_mnt" 2> /dev/null; then
          ok "Unmounted: $_mnt"
        else
          warn "Could not unmount: $_mnt -- still in use (active logging)"
          warn "This mount will be released on reboot."
          warn "After rebooting, run: rm -rf /var/www/htdocs/tn"
        fi
      done
    fi

    # Attempt removal -- may be partial if a log mount is still active
    if rm -rf "/var/www/htdocs/tn" 2> /dev/null; then
      ok "Removed: /var/www/htdocs/tn"
    else
      warn "/var/www/htdocs/tn not fully removed -- active mount still present."
      warn "After the required reboot, run: rm -rf /var/www/htdocs/tn"
    fi
  else
    info "/var/www/htdocs/tn already absent."
  fi

  log "Uninstall complete. Log directory will now be removed."
  if [ -d "$LOG_DIR" ]; then
    rm -rf "$LOG_DIR"
  fi
fi

# =============================================================================
# COMPLETE
# =============================================================================
echo ""
echo "============================================================"
printf "  ${BOLD}Uninstall complete.${NC}\n"
echo "============================================================"
echo ""
printf "  ${YELLOW}ACTION REQUIRED: Reboot this machine.${NC}\n"
printf "  Hostname, gateway, and interface configuration will not\n"
printf "  take effect until the system restarts.\n"
echo ""
printf "  ${YELLOW}If the TN CA certificate was distributed to browsers${NC}\n"
printf "  ${YELLOW}or devices on your network, remove it from those now.${NC}\n"
echo ""

exit 0
