# ============================================================================
# MODULE: TNSecurity.pm
# PURPOSE: Cryptographic primitives, session signing, CSRF, password hashing,
#          key management, and security logging.
# VERSION: 2.1.0
#
# ROLE IN THE STACK:
#   TNSecurity is the cryptographic core. It provides all primitives that
#   touch keys, secrets, or hashes. No other module implements crypto directly.
#
# RESPONSIBILITIES:
#   1. Password hashing    -- PBKDF2-HMAC-SHA256 (100,000 iterations) via
#                             Crypt::PBKDF2. Legacy SHA-256 (10,000 rounds)
#                             accepted for backward compat; TNAuth transparently
#                             rehashes to PBKDF2 on next successful login.
#   2. Session signing     -- sign_session_id() / verify_session_id() using
#                             HMAC-SHA256 with data/keys/session.key.
#                             Cookie value = session_id.hmac_hex(session_id).
#   3. CSRF tokens         -- Deterministic time-window tokens: HMAC-SHA256
#                             of "csrf:W" where W = floor(time/lifetime).
#                             Current and previous window accepted to handle
#                             boundary race conditions.
#   4. HMAC helper         -- hmac_hex() used by control.pl for password reset
#                             tokens. Named key ('session' or default hmac.key).
#   5. Recovery codes      -- hash_recovery_code() / verify_recovery_hash()
#                             using sha256_hex. No salt needed: codes are long,
#                             random, and single-use.
#   6. Key management      -- read_key() / generate_key(). Missing key files
#                             are always fatal -- no silent auto-generation.
#   7. Random generation   -- generate_random_string() from /dev/urandom,
#                             generate_token() = sha256_hex(random + time).
#   8. Security logging    -- log_security_event() writes to data/logs/security.log
#                             and via syslog logger(1).
#   9. HTTP headers        -- print_secure_headers() for JSON API responses
#                             from control.pl (TNWAF covers file/HTML responses).
#
# SRI NOTE:
#   TNSecurity does NOT generate or validate SRI hashes. That responsibility
#   belongs exclusively to TN_SUBSTITUTE.sh (deploy time, writes TNWAF.pm)
#   and TNWAF::serve_file() (runtime, verifies before serving JS assets).
#
# INTEGRATION:
#   Loaded by  : control.pl, TNAuth.pm, TNSecurityCheck.pm
#   Depends on : TNEnv (paths), TNConfig (devel mode, logging config)
#   Key files  : data/keys/session.key, data/keys/hmac.key
#                (generated by TN_UTM_INSTALLER.sh at install time)
#
# AUTHOR: DAVID PETER, TANGENT NETWORKS
# ============================================================================

package TNSecurity;
use strict;
use warnings;

use File::Basename;
use Cwd 'abs_path';

BEGIN {
    my $lib_path = dirname(__FILE__);
    $lib_path = abs_path($lib_path) if -d $lib_path;
    if ( $lib_path =~ m{^([-/\w.]+)$} ) {
        unshift @INC, $1 unless grep { $_ eq $1 } @INC;
    }
}

use TNEnv;
use Digest::SHA qw(sha256_hex hmac_sha256 hmac_sha256_hex);
use MIME::Base64;
use Time::HiRes qw(time);
use Fcntl       qw(:flock);
use Crypt::PBKDF2;
use TNConfig;

our $VERSION = '2.1.0';

# =============================================
# CHROOT-AWARE PATH HELPERS
# =============================================

sub get_base_dir {
    return TNEnv::get_app_root();
}

sub get_key_dir {
    my $base = get_base_dir();
    my $path = File::Spec->catdir( $base, 'data', 'keys' );
    return undef if $path =~ /\.\./;
    if ( $path =~ m{^([-/\w.]+)$} ) { return $1 }
    return undef;
}

sub get_session_key_file {
    my $key_dir = get_key_dir() or return undef;
    my $path    = File::Spec->catfile( $key_dir, 'session.key' );
    return undef if $path =~ /\.\./;
    if ( $path =~ m{^([-/\w.]+)$} ) { return $1 }
    return undef;
}

sub get_hmac_key_file {
    my $key_dir = get_key_dir() or return undef;
    my $path    = File::Spec->catfile( $key_dir, 'hmac.key' );
    return undef if $path =~ /\.\./;
    if ( $path =~ m{^([-/\w.]+)$} ) { return $1 }
    return undef;
}

sub get_log_file {
    my $base = get_base_dir();
    my $path = File::Spec->catfile( $base, 'data', 'logs', 'security.log' );
    return undef if $path =~ /\.\./;
    if ( $path =~ m{^([-/\w.]+)$} ) { return $1 }
    return undef;
}

# =============================================
# PASSWORD HASHING
# =============================================

# Algorithm versioning: hashes stored in the DB carry a prefix so that
# verify_password knows which algorithm was used.
#
#   Legacy (no prefix): iterated SHA-256, 10,000 rounds -- accepted for
#                       backward compatibility. TNAuth rehashes on next login.
#   Current: "pbkdf2:<hex>" -- PBKDF2-HMAC-SHA256, 100,000 iterations,
#                             via Crypt::PBKDF2 (p5-Crypt-PBKDF2-0.161520).
#
# Dependencies confirmed present in chroot:
#   p5-Crypt-PBKDF2-0.161520
#   p5-Type-Tiny-2.008003
#   p5-Moose-2.4000
#
# PBKDF2_ITERATIONS is a named constant -- changing it invalidates all existing
# hashes and requires a migration step.
use constant PBKDF2_ITERATIONS => 100_000;
use constant PBKDF2_PREFIX     => 'pbkdf2:';

# Module-level object -- constructed once at load time, reused on every call.
# HMAC-SHA256 / 100,000 iterations / 32-byte derived key (one SHA-256 block).
my $_pbkdf2 = Crypt::PBKDF2->new(
    hash_class => 'HMACSHA2',
    hash_args  => { sha_size => 256 },
    iterations => PBKDF2_ITERATIONS,
    output_len => 32,
);

sub hash_password {
    my ( $password, $salt ) = @_;
    $salt //= generate_salt();

    # PBKDF2() returns raw bytes; unpack to hex for storage.
    my $dk = $_pbkdf2->PBKDF2( $salt, $password );
    return ( PBKDF2_PREFIX . unpack( 'H*', $dk ), $salt );
}

# needs_rehash: true when the stored hash uses the legacy SHA-256 algorithm.
# TNAuth::authenticate_user calls this and upgrades transparently on success.
sub needs_rehash {
    my ($stored_hash) = @_;
    return 0 unless defined $stored_hash;
    return index( $stored_hash, PBKDF2_PREFIX ) != 0;
}

sub verify_password {
    my ( $password, $stored_hash, $salt ) = @_;

    if ( index( $stored_hash, PBKDF2_PREFIX ) == 0 ) {

        # Current algorithm: PBKDF2-HMAC-SHA256 via Crypt::PBKDF2
        my ( $computed, undef ) = hash_password( $password, $salt );
        return timing_safe_compare( $computed, $stored_hash );
    }
    else {
        # Legacy algorithm: iterated SHA-256, 10,000 rounds.
        # Accepted for backward compatibility; TNAuth rehashes on success.
        my $hash = $password . $salt;
        for ( 1 .. 10000 ) { $hash = sha256_hex($hash); }
        return timing_safe_compare( $hash, $stored_hash );
    }
}

# Recovery codes use a simpler scheme than passwords: sha256_hex($code).
# No salt is needed because recovery codes are long, random, and single-use —
# they are not susceptible to the dictionary attacks that salting defends against.
# The schema stores code_hash; these two functions define the contract so that
# generate_recovery_codes() (future) and verify_recovery_code() (TNAuth) agree.

sub hash_recovery_code {
    my ($code) = @_;
    return sha256_hex($code);
}

sub verify_recovery_hash {
    my ( $code, $stored_hash ) = @_;
    return timing_safe_compare( sha256_hex($code), $stored_hash );
}

sub generate_salt {
    return generate_random_string(32);
}

# =============================================
# SESSION ID SIGNING
# =============================================

sub sign_session_id {
    my ($session_id) = @_;

    my $key       = read_key( get_session_key_file() );
    my $signature = hmac_sha256_hex( $session_id, $key );

    return $session_id . '.' . $signature;
}

sub verify_session_id {
    my ($signed_session) = @_;

    return undef unless $signed_session;

    my ( $session_id, $signature ) = split( /\./, $signed_session, 2 );
    return undef unless $session_id && $signature;

    my $key                = read_key( get_session_key_file() );
    my $expected_signature = hmac_sha256_hex( $session_id, $key );

    return undef unless timing_safe_compare( $signature, $expected_signature );

    return $session_id;
}

# =============================================
# HMAC HELPER
# =============================================
# Named-key HMAC used by control.pl reset token system.
# key_name maps to a key file:
#   'session'  -> data/keys/session.key  (same key as session signing)
#   anything else -> data/keys/hmac.key
# Using the session key for reset tokens is intentional -- no new key
# file needed, and the purpose tag ':reset' in the HMAC input prevents
# a reset token from being replayed as a session signature or vice versa.

sub hmac_hex {
    my ( $data, $key_name ) = @_;
    my $key_file =
      ( $key_name eq 'session' )
      ? get_session_key_file()
      : get_hmac_key_file();
    my $key = read_key($key_file);
    return hmac_sha256_hex( $data, $key );
}

# =============================================
# CSRF TOKENS
# =============================================

sub generate_csrf_token {
    if ( TNConfig::is_devel_mode() ) {
        log_security_event( 'debug', 'DEVEL: CSRF token generated (dev mode)',
            '' );
        return hmac_sha256_hex( 'devel:csrf:' . int( time() ), 'devel' );
    }

    # Deterministic time-window token: HMAC-SHA256("csrf:W", hmac_key)
    # where W = floor(time() / TOKEN_LIFETIME).
    #
    # Being deterministic is what makes this verifiable: validate_csrf_token
    # re-derives the expected value for the current and previous window and
    # does a real timing-safe HMAC comparison. Any 64-char hex string a client
    # submits is checked against the derived value -- not just its format.
    my $token_lifetime = TNConfig::get_config( 'csrf', 'TOKEN_LIFETIME' )
      // 3600;
    $token_lifetime = 60 if $token_lifetime < 60;
    my $key    = read_key( get_hmac_key_file() );
    my $window = int( time() / $token_lifetime );
    return hmac_sha256_hex( "csrf:$window", $key );
}

sub validate_csrf_token {
    my ($token) = @_;

    if ( TNConfig::is_devel_mode() ) {
        log_security_event( 'debug', 'DEVEL: CSRF validation skipped', '' );
        return 1;
    }

    return 0 unless $token;
    return 0 unless $token =~ /^[a-f0-9]{64}$/;

    # Re-derive the token for the current window and the one before it.
    # Accepting the previous window handles the case where a token was
    # fetched just before a boundary and used just after it.
    my $token_lifetime = TNConfig::get_config( 'csrf', 'TOKEN_LIFETIME' )
      // 3600;
    $token_lifetime = 60 if $token_lifetime < 60;
    my $key    = read_key( get_hmac_key_file() );
    my $window = int( time() / $token_lifetime );

    return 1
      if timing_safe_compare( $token, hmac_sha256_hex( "csrf:$window", $key ) );
    return 1
      if timing_safe_compare( $token,
        hmac_sha256_hex( "csrf:" . ( $window - 1 ), $key ) );

    log_security_event( 'warning', 'CSRF_TOKEN_INVALID', '' );
    return 0;
}

# =============================================
# INPUT VALIDATION
# =============================================
sub validate_username {
    my ($username) = @_;
    return 0 unless defined $username;
    return $username =~ /^[a-zA-Z0-9_-]{3,32}$/;
}

sub validate_email {
    my ($email) = @_;
    return 0 unless defined $email;
    return $email =~ /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
}

sub sanitize_input {
    my ($input) = @_;
    return '' unless defined $input;

    # Remove control characters
    $input =~ s/[\x00-\x1F\x7F]//g;

    return $input;
}

sub untaint_filepath {
    my ($path) = @_;
    return undef unless defined $path;

    # Reject any path containing a parent-directory traversal sequence.
    # This check runs before the pattern match so taint mode cannot be
    # satisfied mechanically while still passing "../../../etc/passwd".
    return undef if $path =~ /\.\./;

    # Allow: absolute or relative paths composed of word chars, slashes,
    # hyphens, and dots (e.g. "session.key", "/var/www/htdocs/tn/data/keys").
    if ( $path =~ m{^([-/\w.]+)$} ) {
        return $1;
    }

    return undef;
}

# =============================================
# RANDOM GENERATION
# =============================================

sub generate_random_string {
    my ($length) = @_;
    $length ||= 32;

    my @chars  = ( 'a' .. 'z', 'A' .. 'Z', '0' .. '9' );
    my $string = '';

    open( my $fh, '<', '/dev/urandom' ) or die "Cannot open /dev/urandom: $!\n";
    binmode($fh);

    my $bytes;
    read( $fh, $bytes, $length );
    close $fh;

    foreach my $byte ( split //, $bytes ) {
        $string .= $chars[ ord($byte) % scalar(@chars) ];
    }

    return $string;
}

sub generate_token {
    my ($length) = @_;
    $length ||= 32;

    my $random = generate_random_string($length);
    return sha256_hex( $random . time() );
}

# =============================================
# KEY MANAGEMENT
# =============================================

sub read_key {
    my ($key_file) = @_;

    my $clean_path = untaint_filepath($key_file);
    unless ($clean_path) {
        die "FATAL: Invalid key file path\n";
    }

    # A missing key file is always a fatal error.
    # Silent auto-generation would invalidate all existing sessions and CSRF
    # tokens without any operator alert. init_db.pl creates keys at install
    # time; if a key disappears in production something has gone badly wrong
    # and rc.d / the operator must be notified immediately via the crash.
    unless ( -f $clean_path ) {
        die
"FATAL: Key file missing: $clean_path -- run init_db.pl to regenerate keys\n";
    }

    open( my $fh, '<', $clean_path )
      or die "FATAL: Cannot read key file $clean_path: $!\n";
    my $key = <$fh>;
    close $fh;

    chomp $key;
    return $key;
}

sub generate_key {
    my ($key_file) = @_;

    my $key = generate_random_string(64);

    # Ensure key directory exists
    my $key_dir = get_key_dir();
    unless ( -d $key_dir ) {
        mkdir $key_dir, 0700 or die "Cannot create key directory: $!\n";
    }

    # Write key
    open( my $fh, '>', $key_file ) or die "Cannot write key file: $!\n";
    print $fh $key;
    close $fh;

    chmod 0600, $key_file;

    return $key;
}

# =============================================
# LOGGING
# =============================================

sub log_security_event {
    my ( $level, $event, $details ) = @_;

    my $timestamp = scalar(localtime);
    my $ip        = $ENV{REMOTE_ADDR} || 'unknown';

    my $log_line = sprintf( "[%s] [%s] [%s] %s - %s\n",
        $timestamp, $level, $ip, $event, $details );

    # Log to file if enabled
    if ( TNConfig::get_config( 'logging', 'LOG_TO_FILE' ) ) {
        log_to_file($log_line);
    }
}

sub log_to_file {
    my ($line) = @_;

    my $log_file = get_log_file() or return;
    my $base     = get_base_dir();
    my $log_dir  = File::Spec->catdir( $base, 'data', 'logs' );

    unless ( -d $log_dir ) {
        mkdir $log_dir, 0750;
    }

    open( my $fh, '>>', $log_file ) or return;
    flock( $fh, LOCK_EX )           or do { close $fh; return };
    print $fh $line;
    close $fh;    # releases flock
}

# =============================================
# UTILITY FUNCTIONS
# =============================================

sub timing_safe_compare {
    my ( $a, $b ) = @_;

    return 0 unless defined $a && defined $b;
    return 0 unless length($a) == length($b);

    my $result = 0;
    for my $i ( 0 .. length($a) - 1 ) {
        $result |= ord( substr( $a, $i, 1 ) ) ^ ord( substr( $b, $i, 1 ) );
    }

    return $result == 0;
}

sub security_enabled {
    my ($feature) = @_;

    return 0 if TNConfig::is_devel_mode();

    my $config_key = "ENABLE_" . uc($feature);
    return TNConfig::get_config( 'security', $config_key ) || 0;
}

# =============================================
# HTTP RESPONSE HEADERS
# =============================================
# print_secure_headers() is the single point of truth for security headers
# on CGI responses. TNWAF::print_headers() covers routed file responses;
# this function covers all JSON API responses from CGI scripts.
#
# Headers emitted:
#   Content-Type              -- always
#   Content-Security-Policy   -- default-src 'self'; no inline unless DEVEL
#   Strict-Transport-Security -- HSTS, 1 year, includeSubDomains
#   Referrer-Policy           -- strict-origin-when-cross-origin
#   Permissions-Policy        -- deny all sensor/hardware APIs
#   X-Frame-Options           -- DENY (belt-and-suspenders with CSP frame-ancestors)
#   X-Content-Type-Options    -- nosniff
#   Cache-Control             -- no-store (unless $cache is true)

sub print_secure_headers {
    my ( $content_type, $cache ) = @_;
    $content_type ||= 'application/json';

    print "Content-Type: $content_type; charset=UTF-8\n";

    # CSP: for JSON API endpoints 'none' for everything except connect-src
    # 'self' (fetch calls back to same origin). Tightened further vs HTML pages.
    print "Content-Security-Policy: default-src 'none'; connect-src 'self'\n";

    # HSTS: tell browsers this origin is HTTPS-only for 1 year.
    # includeSubDomains covers any sub-pages served from sub-domains.
    # NOTE: Only effective over HTTPS -- harmless but ignored over HTTP.
    print "Strict-Transport-Security: max-age=31536000; includeSubDomains\n";

    print "Referrer-Policy: strict-origin-when-cross-origin\n";
    print
"Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=()\n";
    print "X-Frame-Options: DENY\n";
    print "X-Content-Type-Options: nosniff\n";

    if ( !$cache ) {
        print "Cache-Control: no-cache, no-store, must-revalidate\n";
        print "Pragma: no-cache\n";
        print "Expires: 0\n";
    }

    print "\n";
}

1;

__END__

=head1 NAME

TNSecurity -- Chroot-aware security functions for TNSecurity Suite

=cut
