#!/usr/bin/perl -T

# SPDX-FileCopyrightText: 2026 David Peter, Tangent Networks
#
# SPDX-License-Identifier: BSD-3-Clause

# ============================================================
# create_user.pl - First Admin Account Creation
# ============================================================
# Location: /usr/local/sbin/create_user.pl
#
# PURPOSE:
#   Creates the first administrator account via command line.
#   Accepts a SQL schema file to initialise a fresh database.
#   Subsequent users register via the web UI using tokens
#   generated by the admin.
#
# USAGE:
#   perl -T /usr/local/sbin/create_user.pl \
#       --schema /path/to/schema.sql
#
# Must be run as root. The script creates the database, then
# sets ownership to www:www 0600 so the web process can access
# it at runtime.
#
# AUTHOR: David Peter, Tangent Networks
# VERSION: 2.4.2
# ============================================================

use strict;
use warnings;
use FindBin qw($RealBin);
use File::Spec;

# ============================================================
# TAINT-SAFE BOOTSTRAP
# ============================================================

BEGIN {
    $ENV{PATH} = '/bin:/usr/bin:/sbin:/usr/sbin';
    delete @ENV{qw(IFS CDPATH ENV BASH_ENV)};

    my $lib_path;

    if ( $FindBin::RealBin =~ m{^([-/\w.]+/data)/scripts$} ) {
        $lib_path = File::Spec->catdir( $1, 'lib' );
    }
    elsif ( -d '/var/www/htdocs/tn/data/lib' ) {
        $lib_path = '/var/www/htdocs/tn/data/lib';
    }
    else {
        die "FATAL: Could not determine library path from: $FindBin::RealBin\n";
    }

    if ( $lib_path =~ m{^([-/\w.]+)$} ) {
        $lib_path = $1;
        unshift @INC, $lib_path;
    }
    else {
        die "FATAL: Library path contains unsafe characters: $lib_path\n";
    }
}

use IPC::Open3;
use Symbol qw(gensym);
use TNEnv;
use TNAuth;
use TNSecurity;

my $MIN_PASSWORD_LENGTH = 12;

# ============================================================
# PRIVILEGE CHECK -- must run as root
# ============================================================
# Root creates the db and sets www:www ownership.
# Do NOT run as www -- www cannot chown files to itself
# and the web user should not have write access to scripts.

unless ( $> == 0 ) {
    print "ERROR: This script must be run as root.\n\n";
    print "  perl -T $0 --schema /path/to/schema.sql\n\n";
    exit 1;
}

# ============================================================
# ARGUMENT PARSING -- `--schema` flag is mandatory
# ============================================================

my $schema_file;

{
    my @argv = @ARGV;
    while (@argv) {
        my $arg = shift @argv;
        if ( $arg eq '--schema' ) {
            $schema_file = shift @argv;
        }
        elsif ( $arg =~ /^--schema=(.+)$/ ) {
            $schema_file = $1;
        }
        else {
            print "ERROR: Unknown argument: $arg\n\n";
            _usage();
            exit 1;
        }
    }

    unless ( defined $schema_file && $schema_file ne '' ) {
        print "ERROR: --schema is required.\n\n";
        _usage();
        exit 1;
    }
}

# Untaint and validate schema file path
my $schema_safe;
if ( $schema_file =~ m{^([-/\w.]+\.sql)$} ) {
    $schema_safe = $1;
}
else {
    die
"ERROR: Schema path contains unsafe characters or wrong extension: $schema_file\n";
}

unless ( -f $schema_safe ) {
    print "ERROR: Schema file not found: $schema_safe\n\n";
    exit 1;
}

unless ( -r $schema_safe ) {
    print "ERROR: Schema file is not readable: $schema_safe\n\n";
    exit 1;
}

# ============================================================
# INITIALISE DATABASE FROM SCHEMA
# ============================================================
# The db path is always determined by TNEnv -- the schema file
# is only a DDL source. Its location has no bearing on where
# the database is created.

my $db_path;
{
    my $db_dir_raw = TNEnv::get_db_path();
    my ($db_dir) = ( $db_dir_raw =~ m{^([-/\w.]+)$} )
      or die "ERROR: TNEnv::get_db_path() returned unsafe path: $db_dir_raw\n";

    $db_path = File::Spec->catfile( $db_dir, 'auth.db' );

    # Re-untaint the assembled path
    ($db_path) = ( $db_path =~ m{^([-/\w./]+\.db)$} )
      or die "ERROR: Could not untaint assembled db path: $db_path\n";
}

if ( -e $db_path ) {
    print "ERROR: Database already exists: $db_path\n";
    print
      "        Remove it first or use emergency_user_repair.pl instead.\n\n";
    exit 1;
}

print "Initialising database from schema...\n";
print "  Schema : $schema_safe\n";
print "  DB     : $db_path\n\n";

{
    # open3 is called with an uninitialised $in_fh so it creates the
    # pipe itself. We then pump the schema into it and close it to
    # signal EOF -- sqlite3 blocks forever if it never sees EOF on stdin.
    # Reading stderr AFTER closing stdin avoids the deadlock that the
    # original code had (passing an already-open fh as the first arg
    # meant sqlite3's stdin was never properly connected, and reading
    # stderr before waitpid could block if stdout filled up first).

    open( my $schema_fh, '<', $schema_safe )
      or die "ERROR: Could not open schema file: $!\n";

    my ( $in_fh, $out_fh, $err_fh );
    $err_fh = gensym;

    my $pid = open3( $in_fh, $out_fh, $err_fh,
        '/usr/local/bin/sqlite3', '-batch', $db_path );

    # Pump schema into sqlite3 then close to signal EOF
    while ( my $line = <$schema_fh> ) {
        print $in_fh $line;
    }
    close $in_fh;
    close $schema_fh;

    my $stderr_output = do { local $/; <$err_fh> };
    waitpid( $pid, 0 );
    my $rc = $? >> 8;    # $? is raw wait status -- shift to get exit code

    if ( $rc != 0 ) {
        $stderr_output //= '';
        die "ERROR: sqlite3 failed to initialise database (exit $rc).\n"
          . ( $stderr_output
            ? "       sqlite3 said: $stderr_output"
            : "       Check schema file for syntax errors.\n" );
    }
}

unless ( -e $db_path ) {
    die "ERROR: sqlite3 ran but db file was not created: $db_path\n";
}

ok("Database initialised");

# ============================================================
# SET OWNERSHIP -- root creates, www:www owns at runtime
# ============================================================

{
    my ($db_path_safe) = ( $db_path =~ m{^([-/\w./]+)$} )
      or die "ERROR: Unsafe characters in db path: $db_path\n";
    my ($db_dir_safe) = ( $db_path_safe =~ m{^([-/\w./]+)/[^/]+$} )
      or die "ERROR: Could not derive directory from: $db_path_safe\n";

    # getpwnam/getgrnam return tainted values under -T -- untaint explicitly
    my $www_uid_raw = getpwnam('www');
    my $www_gid_raw = getgrnam('www');

    unless ( defined $www_uid_raw ) {
        print "ERROR: 'www' user not found on this system.\n";
        exit 1;
    }

    my ($www_uid) = ( $www_uid_raw =~ /^(\d+)$/ )
      or die "ERROR: Could not untaint www uid\n";
    my ($www_gid) = ( $www_gid_raw =~ /^(\d+)$/ )
      or die "ERROR: Could not untaint www gid\n";

    chown $www_uid, $www_gid, $db_dir_safe;
    chown $www_uid, $www_gid, $db_path_safe;
    chmod 0750, $db_dir_safe;
    chmod 0600, $db_path_safe;

    printf "  Ownership set : %s (www:www 0600)\n\n", $db_path_safe;
}

print "=" x 60 . "\n";
print "  TNSecurity - First Admin Account Creation\n";
print "  Tangent Networks\n";
print "=" x 60 . "\n\n";

# Refuse to run if users already exist (shouldn't happen with a
# freshly created db, but belt-and-braces check)
my $status = TNAuth::check_registration_status();
unless ( $status->{is_first_user} ) {
    print "ERROR: Users already exist in the database.\n";
    print "       Use the web UI or emergency_user_repair.pl instead.\n\n";
    exit 1;
}

print "No users found. Creating the first administrator account.\n\n";

# ============================================================
# RESCUE CONTEXT & WARNING CONFIRMATION
# ============================================================

print "!" x 60 . "\n";
print "  CRITICAL RESCUE NOTICE & OPERATIONAL IMPACTS\n";
print "!" x 60 . "\n";
print "You are initialising a completely FRESH database instance.\n";
print "If you are running this to rescue an un-resettable user:\n\n";
print "  1. INVITATION BLINDSPOT:\n";
print "     Existing active or pending invite tokens will not exist in\n";
print "     this instance. You cannot invite or register subsequent\n";
print "     users until you log in and generate completely new tokens.\n";
print "\n";
print "  2. RECOVERY STRANDING:\n";
print "     This user is provisioned without security Q&A or recovery\n";
print "     tokens. Password resets via WebUI will remain non-functional\n";
print "     until manually configured post-login.\n";
print "!" x 60 . "\n";

print "Do you explicitly understand and accept this system state? (Type YES): ";
my $confirmation = <STDIN>;
chomp $confirmation;

if ( $confirmation ne 'YES' ) {
    print
      "Aborting execution due to lack of operational context validation.\n\n";
    exit 1;
}
print "Context confirmed. Proceeding with user creation.\n\n";

# ============================================================
# COLLECT USERNAME
# ============================================================

print "Username (3-32 chars, letters, numbers, _ and -): ";
my $raw_username = <STDIN>;
chomp $raw_username;

my $username;
if ( $raw_username =~ /^([a-zA-Z0-9_-]{3,32})$/ ) {
    $username = $1;
}
else {
    die "ERROR: Invalid username format.\n";
}

# ============================================================
# COLLECT EMAIL (OPTIONAL)
# ============================================================

print "Email (optional -- press Enter to skip): ";
my $raw_email = <STDIN>;
chomp $raw_email;
$raw_email =~ s/^\s+|\s+$//g;

my $email;
if ( $raw_email ne '' ) {
    if ( $raw_email =~ /^([^\s\@]+\@[^\s\@]+\.[^\s\@]+)$/ ) {
        $email = $1;
    }
    else {
        die "ERROR: Invalid email format.\n";
    }
}

# ============================================================
# COLLECT PASSWORD
# ============================================================

print "\nPassword requirements:\n";
print "  At least $MIN_PASSWORD_LENGTH characters\n";
print "  One uppercase letter\n";
print "  One lowercase letter\n";
print "  One number\n";
print "  One special character\n\n";

my $password;
my $attempts = 0;

while ( $attempts < 3 ) {
    print "Password: ";
    system( '/bin/stty', '-echo' );
    my $pass1 = <STDIN>;
    system( '/bin/stty', 'echo' );
    chomp $pass1;
    print "\n";

    print "Confirm password: ";
    system( '/bin/stty', '-echo' );
    my $pass2 = <STDIN>;
    system( '/bin/stty', 'echo' );
    chomp $pass2;
    print "\n";

    unless ( $pass1 eq $pass2 ) {
        print "ERROR: Passwords do not match.\n\n";
        $attempts++;
        next;
    }

    my @errors;
    push @errors, "Must be at least $MIN_PASSWORD_LENGTH characters"
      if length($pass1) < $MIN_PASSWORD_LENGTH;
    push @errors, "Must contain an uppercase letter" unless $pass1 =~ /[A-Z]/;
    push @errors, "Must contain a lowercase letter"  unless $pass1 =~ /[a-z]/;
    push @errors, "Must contain a number"            unless $pass1 =~ /[0-9]/;
    push @errors, "Must contain a special character"
      unless $pass1 =~ /[^A-Za-z0-9]/;

    if (@errors) {
        print "ERROR: Password does not meet requirements:\n";
        print "  - $_\n" for @errors;
        print "\n";
        $attempts++;
        next;
    }

    $password = $pass1;
    last;
}

die "ERROR: Too many failed attempts.\n" if $attempts >= 3;

# ============================================================
# CREATE ACCOUNT VIA TNAuth
# ============================================================

print "\nCreating account...\n";

my $result = TNAuth::register_user(
    $username,
    $password,
    $email || undef,
    [],    # No security questions at this stage -- set via web UI
    ''     # No token needed for first user
);

if ( $result->{success} ) {
    print "\n";
    print "=" x 60 . "\n";
    print "Account created successfully.\n";
    print "=" x 60 . "\n\n";
    printf "  Username : %s\n",   $username;
    printf "  Email    : %s\n",   $email || 'not set';
    printf "  Role     : %s\n",   $result->{role};
    printf "  User ID  : %s\n",   $result->{user_id};
    printf "  DB       : %s\n\n", $db_path;
    print "NOTE: Security questions are not set. The user should\n";
    print "      configure them after first login so the web-based\n";
    print "      password reset flow will be available.\n\n";
    print "You can now log in at: https://%%INT_IP4%%/\n\n";
    exit 0;
}
else {
    die "ERROR: Failed to create account: $result->{error}\n";
}

# ============================================================
# HELPERS
# ============================================================

sub ok {
    printf "  [+] %s\n", $_[0];
}

sub _usage {
    print "USAGE:\n";
    print
"  perl -T /usr/local/sbin/create_user.pl --schema /path/to/schema.sql\n\n";
    print
"  --schema   Path to the SQL schema file (DDL) used to initialise the database.\n";
    print
"             The database is always created at the path configured in TNEnv\n";
    print "             (auth.db in the configured db directory).\n";
    print "             Must be run as root.\n\n";
    print "EXAMPLE:\n";
    print "  perl -T /usr/local/sbin/create_user.pl \\\n";
    print "       --schema /var/www/htdocs/tn/data/db/schema.sql\n\n";
}
