#!/usr/bin/perl -T

# SPDX-FileCopyrightText: 2026 David Peter, Tangent Networks
#
# SPDX-License-Identifier: BSD-3-Clause

# /usr/local/sbin/pf_validator.pl
#
# Called by pf_monitor.sh (root) to:
#   1. Read all user-input queue files
#   2. Deduplicate against existing blocklist/bogons
#   3. Assemble /queue/pf-rules/staging/pf-addons.conf
#   4. Print structured output lines for pf_monitor.sh to parse:
#        STATS_JSON:{...}
#        WARNINGS_JSON:[...]
#   5. Exit 0 on success, non-zero on hard failure
#
# PRIVILEGE: runs as root (called from pf_monitor.sh)
# SECURITY: Taint mode enabled, safe file operations, validated paths

use strict;
use warnings;
use JSON::PP;
use File::Spec;
use POSIX qw(strftime);

# Clean environment for taint mode
$ENV{PATH} = '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin';
delete @ENV{ 'IFS', 'CDPATH', 'ENV', 'BASH_ENV' };

# ============================================
# CONFIGURATION
# ============================================
my $QUEUE_BASE = '/var/www/htdocs/tn/data/services/queue/pf-rules';
my $USER_INPUT = "$QUEUE_BASE/user-input";
my $STAGING    = "$QUEUE_BASE/staging";
my $BASE_SNAP  = "$QUEUE_BASE/base-snapshot/all-existing-ips.txt";
my $LOG_FILE   = '/var/www/tmp/pf_validator.log';

# GeoIP country data -- populated by get_geoip_data.pl
# ASN resolution is handled separately by pf_asn_resolve.sh (not the validator)
my $GEOIP_BASE = '/var/www/htdocs/tn/data/db/GeoIP';
my $GEOIP_V4   = "$GEOIP_BASE/ipv4";
my $GEOIP_V6   = "$GEOIP_BASE/ipv6";

# ============================================
# LOGGING
# ============================================
sub log_msg {
    my $msg = shift;
    my $ts  = strftime( '%Y-%m-%d %H:%M:%S', localtime );
    open( my $fh, '>>', $LOG_FILE ) or return;
    print $fh "[$ts] [pf_validator] $msg\n";
    close $fh;
    print "$msg\n";    # also goes to pf_monitor's full-context.txt
}

# ============================================
# LOAD EXISTING IPs FOR DEDUPLICATION
# ============================================
sub load_existing_ips {
    my %seen;
    if ( -f $BASE_SNAP ) {
        open( my $fh, '<', $BASE_SNAP ) or return %seen;
        while ( my $line = <$fh> ) {
            chomp $line;
            $line =~ s/^\s+|\s+$//g;
            next if $line =~ /^#/ || $line eq '';
            $seen{ lc($line) } = 1;
        }
        close $fh;
    }
    return %seen;
}

# ============================================
# VALIDATE IP/CIDR (same logic as pf_write_input.pl)
# ============================================
sub valid_ip_cidr {
    my ($ip) = @_;

    # IPv4
    return 1
      if $ip =~
/^(?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?)$/;

    # IPv4 CIDR
    if ( $ip =~
m{^((?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?))/(\d+)$}
      )
    {
        return 1 if $2 >= 0 && $2 <= 32;
    }

    # IPv6 (simplified)
    return 1 if $ip =~ /^[0-9a-fA-F:]+(?:\/\d{1,3})?$/;

    return 0;
}

# ============================================
# MAIN
# ============================================
log_msg("=== pf_validator.pl started ===");

# Ensure staging dir exists
unless ( -d $STAGING ) {
    mkdir $STAGING, 0755 or die "Cannot create $STAGING: $!";
}

my %existing   = load_existing_ips();
my @conf_lines = ();                    # lines for pf-addons.conf
my %stats      = (
    ip_added        => 0,
    asn_added       => 0,
    geoip_countries => 0,
    feeds_added     => 0,
    rejected        => 0,
    duplicates      => 0,
    custom_rules    => 0,
);
my @warnings = ();

# ============================================
# SECTION HEADER HELPER
# ============================================
sub section {
    my $title = shift;
    push @conf_lines, "";
    push @conf_lines, "# " . "=" x 60;
    push @conf_lines, "# $title";
    push @conf_lines, "# " . "=" x 60;
}

push @conf_lines, "# pf-addons.conf - Generated by pf_validator.pl";
push @conf_lines, "# " . strftime( '%Y-%m-%d %H:%M:%S', localtime );
push @conf_lines, "# Loaded via: pfctl -a addons -f /etc/pf/pf-addons.conf";
push @conf_lines, "";

# ============================================
# 1. IP BLOCK LIST
# ============================================
{
    my $file = "$USER_INPUT/ip-block.txt";
    my @block_ips;

    if ( -f $file ) {
        open( my $fh, '<', $file ) or do {
            push @warnings, "Cannot read ip-block.txt: $!";
            goto SKIP_IP_BLOCK;
        };
        while ( my $line = <$fh> ) {
            chomp $line;
            $line =~ s/^\s+|\s+$//g;
            next if $line =~ /^#/ || $line eq '';

            unless ( valid_ip_cidr($line) ) {
                log_msg("REJECT ip-block: $line (invalid format)");
                $stats{rejected}++;
                next;
            }
            if ( $existing{ lc($line) } ) {
                log_msg("DEDUP ip-block: $line (already in blocklist/bogons)");
                $stats{duplicates}++;
                next;
            }
            push @block_ips, $line;
            $stats{ip_added}++;
        }
        close $fh;
    }

    if (@block_ips) {
        section("USER IP BLOCK LIST");
        push @conf_lines, 'table <user_block_ips> persist { \\';
        for my $i ( 0 .. $#block_ips ) {
            my $comma = ( $i < $#block_ips ) ? ', \\' : ' \\';
            push @conf_lines, "    $block_ips[$i]$comma";
        }
        push @conf_lines, '}';
        push @conf_lines, 'block drop quick from <user_block_ips>';
        push @conf_lines, 'block drop quick to <user_block_ips>';
        log_msg( "IP block: " . scalar(@block_ips) . " entries" );
    }

  SKIP_IP_BLOCK:
}

# ============================================
# 2. IP PASS LIST
# ============================================
{
    my $file = "$USER_INPUT/ip-pass.txt";
    my @pass_ips;

    if ( -f $file ) {
        open( my $fh, '<', $file ) or goto SKIP_IP_PASS;
        while ( my $line = <$fh> ) {
            chomp $line;
            $line =~ s/^\s+|\s+$//g;
            next if $line =~ /^#/ || $line eq '';
            unless ( valid_ip_cidr($line) ) {
                $stats{rejected}++;
                next;
            }
            push @pass_ips, $line;
            $stats{ip_added}++;
        }
        close $fh;
    }

    if (@pass_ips) {
        section("USER IP PASS LIST");
        push @conf_lines, 'table <user_pass_ips> persist { \\';
        for my $i ( 0 .. $#pass_ips ) {
            my $comma = ( $i < $#pass_ips ) ? ', \\' : ' \\';
            push @conf_lines, "    $pass_ips[$i]$comma";
        }
        push @conf_lines, '}';
        push @conf_lines, 'pass quick from <user_pass_ips>';
        push @conf_lines, 'pass quick to <user_pass_ips>';
        log_msg( "IP pass: " . scalar(@pass_ips) . " entries" );
    }

  SKIP_IP_PASS:
}

# ============================================
# 3. ASN BLOCK LIST
#
# ARCHITECTURE NOTE:
#   The validator does NOT resolve ASN -> CIDRs.
#   CIDR resolution is done by pf_asn_resolve.sh (root cron, outside chroot)
#   which reads asn-block.txt and populates the live PF table directly via:
#       pfctl -t user_asn_block -T add <cidrs>
#
#   The validator's only job here is to:
#     a) Validate the ASN format
#     b) Emit a persistent empty table + block rule into pf-addons.conf
#     c) pf_asn_resolve.sh fills the table immediately after apply
#        and again on its cron schedule
# ============================================
{
    my $file = "$USER_INPUT/asn-block.txt";
    my @asns;

    if ( -f $file ) {
        open( my $fh, '<', $file ) or goto SKIP_ASN;
        while ( my $line = <$fh> ) {
            chomp $line;
            $line =~ s/^\s+|\s+$//g;
            next if $line =~ /^#/ || $line eq '';
            if ( $line =~ /^(AS\d{1,10})$/i ) {
                push @asns, uc($1);
                $stats{asn_added}++;
            }
            else {
                $stats{rejected}++;
                log_msg("REJECT asn: $line (invalid format)");
            }
        }
        close $fh;
    }

    if (@asns) {
        section("USER ASN BLOCK LIST");

    # Emit a single persistent table (starts empty, filled by pf_asn_resolve.sh)
    # and a single block rule referencing it.
    # All user ASNs share one table - the resolve script manages membership.
        push @conf_lines, "# ASNs: " . join( ', ', @asns );
        push @conf_lines,
          "# CIDRs populated by pf_asn_resolve.sh (cron, runs as root)";
        push @conf_lines, 'table <user_asn_block> persist';
        push @conf_lines, 'block drop quick from <user_asn_block>';
        push @conf_lines, 'block drop quick to <user_asn_block>';

        log_msg( "ASN: "
              . scalar(@asns)
              . " ASNs queued for resolution: "
              . join( ', ', @asns ) );
        push @warnings,
"ASN rules staged - pf_asn_resolve.sh will populate table within its next cron cycle";
    }

  SKIP_ASN:
}

# ============================================
# 4. GEOIP POLICY
# Reads geoip-policy.json -> country code -> CIDRs
# Uses /etc/pf/geoip/ directory (pre-populated by separate fetch job)
# Falls back to warning if files not found
# ============================================
{
    my $file = "$USER_INPUT/geoip-policy.json";

    if ( -f $file && -s $file ) {
        my $json_text;
        open( my $fh, '<', $file ) or goto SKIP_GEOIP;
        { local $/; $json_text = <$fh>; }
        close $fh;

        my $policy;
        eval { $policy = decode_json($json_text); };
        if ($@) {
            push @warnings, "GeoIP: invalid JSON in geoip-policy.json";
            goto SKIP_GEOIP;
        }

        my $action =
          ( $policy->{action} || 'block' ) =~ /^(block|pass)$/ ? $1 : 'block';
        my $countries = $policy->{countries} || [];

        unless ( ref($countries) eq 'ARRAY' && @$countries ) {
            goto SKIP_GEOIP;
        }

        section(
            "GEOIP POLICY ($action " . scalar(@$countries) . " countries)" );

        my @loaded_countries;
        for my $cc (@$countries) {
            next unless $cc =~ /^[A-Z]{2}$/;

            # GeoIP data pre-fetched by get_geoip_data.pl
            # ipv4: /GeoIP/ipv4/XX.txt   ipv6: /GeoIP/ipv6/XX.txt
            my $v4_file = "$GEOIP_V4/$cc.txt";
            my $v6_file = "$GEOIP_V6/$cc.txt";

            my $has_v4 = ( -f $v4_file && -s $v4_file );
            my $has_v6 = ( -f $v6_file && -s $v6_file );

            unless ( $has_v4 || $has_v6 ) {
                push @warnings,
"GeoIP: $cc - no data files found (checked $v4_file and $v6_file)";
                log_msg("WARNING: GeoIP $cc - no data files");
                next;
            }

            my @cidrs;

            # Load IPv4
            if ($has_v4) {
                open( my $gfh, '<', $v4_file ) or do {
                    push @warnings, "GeoIP: $cc - cannot read $v4_file: $!";
                    goto NEXT_COUNTRY;
                };
                while ( my $line = <$gfh> ) {
                    chomp $line;
                    $line =~ s/^\s+|\s+$//g;
                    next if $line =~ /^#/ || $line eq '';
                    push @cidrs, $line if valid_ip_cidr($line);
                }
                close $gfh;
            }

            # Load IPv6
            if ($has_v6) {
                open( my $gfh, '<', $v6_file ) or do {
                    push @warnings, "GeoIP: $cc - cannot read $v6_file: $!";
                    goto NEXT_COUNTRY;
                };
                while ( my $line = <$gfh> ) {
                    chomp $line;
                    $line =~ s/^\s+|\s+$//g;
                    next if $line =~ /^#/ || $line eq '';
                    push @cidrs, $line if valid_ip_cidr($line);
                }
                close $gfh;
            }

            if (@cidrs) {
                my $tbl = "geoip_\L$cc\E";
                push @conf_lines, "# GeoIP: $cc (" . scalar(@cidrs) . " CIDRs)";
                push @conf_lines, "table <$tbl> persist { \\";
                for my $i ( 0 .. $#cidrs ) {
                    my $sep = ( $i < $#cidrs ) ? ', \\' : ' \\';
                    push @conf_lines, "    $cidrs[$i]$sep";
                }
                push @conf_lines, '}';
                if ( $action eq 'block' ) {
                    push @conf_lines, "block drop quick from <$tbl>";
                    push @conf_lines, "block drop quick to <$tbl>";
                }
                else {
                    push @conf_lines, "pass quick from <$tbl>";
                    push @conf_lines, "pass quick to <$tbl>";
                }
                push @loaded_countries, $cc;
                $stats{geoip_countries}++;
                log_msg( "GeoIP $cc: " . scalar(@cidrs) . " CIDRs ($action)" );
            }

          NEXT_COUNTRY:
        }

        unless (@loaded_countries) {
            push @warnings,
"GeoIP: no country data loaded - ensure get_geoip_data.pl has been run";
        }
    }

  SKIP_GEOIP:
}

# ============================================
# 5. THREAT FEED URLS
# Fetches URLs and extracts valid IPs/CIDRs
# ============================================
{
    my $file = "$USER_INPUT/feed-urls.txt";
    my @feed_entries;

    if ( -f $file ) {
        open( my $fh, '<', $file ) or goto SKIP_FEEDS;
        while ( my $line = <$fh> ) {
            chomp $line;
            $line =~ s/^\s+|\s+$//g;
            next if $line =~ /^#/ || $line eq '';

            # Format: action:URL
            if ( $line =~ m{^(block|pass):(https?://\S+)$} ) {
                push @feed_entries, { action => $1, url => $2 };
            }
            else {
                push @warnings, "Feed: skipping malformed line: $line";
                $stats{rejected}++;
            }
        }
        close $fh;
    }

    if (@feed_entries) {
        section("THREAT INTELLIGENCE FEEDS");

        # Check intel.txt (protected feeds) for duplicate URLs
        my %protected_urls;
        my $intel_file = '/var/www/htdocs/tn/data/db/pf/intel.txt';
        if ( -f $intel_file ) {
            open( my $ifh, '<', $intel_file ) or ();
            while (<$ifh>) {
                chomp;
                $protected_urls{$2} = 1 if /^(\w+):\s*(\S+)/;
            }
            close $ifh;
        }

        my $feed_idx = 0;
        for my $entry (@feed_entries) {
            my $url    = $entry->{url};
            my $action = $entry->{action};

            if ( $protected_urls{$url} ) {
                push @warnings,
                  "Feed: $url is already a protected system feed - skipped";
                $stats{duplicates}++;
                next;
            }

            $feed_idx++;
            log_msg("Fetching feed $feed_idx: $url");

            # Fetch using ftp(1) - safe pipe execution, no shell
            my $tmpfile = "/tmp/pf_feed_$$.tmp";

            # Untaint PID for temp file name
            my $safe_pid = $$;
            if ( $safe_pid =~ /^(\d+)$/ ) {
                $safe_pid = $1;
                $tmpfile  = "/tmp/pf_feed_${safe_pid}.tmp";
            }
            else {
                $tmpfile = "/tmp/pf_feed_tmp.txt";
            }

          # Untaint URL (already validated earlier but taint mode requires this)
            my $safe_url = $url;
            unless (
                $url =~ m{^(https?://[a-zA-Z0-9\-._~:/?#\[\]@!$&'()*+,;=%]+)$} )
            {
                push @warnings, "Feed: invalid URL format: $url";
                $stats{rejected}++;
                next;
            }
            $safe_url = $1;

            # Safe execution - list form prevents shell injection
            my $fetch_exit = system( 'ftp', '-o', $tmpfile, '-V', $safe_url );
            $fetch_exit = $fetch_exit >> 8;

            unless ( $fetch_exit == 0 && -f $tmpfile && -s $tmpfile ) {
                push @warnings,
                  "Feed: failed to fetch $url (exit code: $fetch_exit)";
                log_msg("WARNING: fetch failed for $url");
                unlink $tmpfile;
                $stats{rejected}++;
                next;
            }

            # Parse IPs/CIDRs from feed
            my @feed_ips;
            open( my $tmp_fh, '<', $tmpfile ) or next;
            while ( my $line = <$tmp_fh> ) {
                chomp $line;
                $line =~ s/^\s+|\s+$//g;
                $line =~ s/#.*$//;         # strip inline comments
                next if $line eq '' || $line =~ /^#/;

                # Some feeds prefix entries
                $line =~ s/^0\.0\.0\.0\s+//;     # hosts-format
                $line =~ s/^127\.0\.0\.1\s+//;

                if ( valid_ip_cidr($line) ) {
                    if ( $existing{ lc($line) } ) {
                        $stats{duplicates}++;
                    }
                    else {
                        push @feed_ips, $line;
                    }
                }
            }
            close $tmp_fh;
            unlink $tmpfile;

            if (@feed_ips) {
                my $safe_idx = sprintf( "%03d", $feed_idx );
                push @conf_lines,
                  "# Feed $feed_idx: $url (" . scalar(@feed_ips) . " entries)";
                push @conf_lines, "table <feed_${safe_idx}> persist { \\";
                for my $i ( 0 .. $#feed_ips ) {
                    my $sep = ( $i < $#feed_ips ) ? ', \\' : ' \\';
                    push @conf_lines, "    $feed_ips[$i]$sep";
                }
                push @conf_lines, '}';
                if ( $action eq 'block' ) {
                    push @conf_lines,
                      "block drop quick from <feed_${safe_idx}>";
                }
                else {
                    push @conf_lines, "pass quick from <feed_${safe_idx}>";
                }
                $stats{feeds_added}++;
                log_msg( "Feed $feed_idx: "
                      . scalar(@feed_ips)
                      . " IPs loaded ($action)" );
            }
            else {
                push @warnings, "Feed $feed_idx ($url): no valid IPs extracted";
                log_msg("WARNING: feed $feed_idx yielded no valid IPs");
            }
        }
    }

  SKIP_FEEDS:
}

# ============================================
# 6. CUSTOM PF RULES
# ============================================
{
    my $file = "$USER_INPUT/custom-rules.txt";
    my @custom_rules;

    if ( -f $file ) {
        open( my $fh, '<', $file ) or goto SKIP_CUSTOM;
        while ( my $line = <$fh> ) {
            chomp $line;
            $line =~ s/^\s+|\s+$//g;
            next if $line =~ /^#/ || $line eq '';

            # Must start with a valid action keyword
            if ( $line =~ /^(pass|block|match)\s/ ) {

                # Reject shell metacharacters
                if ( $line =~ /[;&|`\$<>]/ ) {
                    push @warnings,
                      "Custom rule rejected (dangerous chars): $line";
                    $stats{rejected}++;
                }
                else {
                    push @custom_rules, $line;
                    $stats{custom_rules}++;
                }
            }
            else {
                push @warnings, "Custom rule rejected (invalid action): $line";
                $stats{rejected}++;
            }
        }
        close $fh;
    }

    if (@custom_rules) {
        section("CUSTOM PF RULES");
        push @conf_lines, @custom_rules;
        log_msg( "Custom rules: " . scalar(@custom_rules) . " added" );
    }

  SKIP_CUSTOM:
}

# ============================================
# WRITE STAGED CONFIG
# ============================================
push @conf_lines, "";
push @conf_lines, "# --- End of pf-addons.conf ---";

my $staged = "$STAGING/pf-addons.conf";

open( my $out_fh, '>', $staged ) or do {
    log_msg("FATAL: cannot write $staged: $!");
    exit 1;
};
print $out_fh join( "\n", @conf_lines ) . "\n";
close $out_fh;

# Set permissions: root owns it, www can read
chown 0, 0, $staged;
chmod 0640, $staged;

log_msg( "Staged config written: $staged (" . scalar(@conf_lines) . " lines)" );
log_msg( "Stats: ip="
      . $stats{ip_added} . " asn="
      . $stats{asn_added}
      . " geoip="
      . $stats{geoip_countries}
      . " feeds="
      . $stats{feeds_added}
      . " custom="
      . $stats{custom_rules}
      . " rejected="
      . $stats{rejected}
      . " dupes="
      . $stats{duplicates} );

if (@warnings) {
    log_msg( "Warnings (" . scalar(@warnings) . "):" );
    log_msg("  - $_") for @warnings;
}

# ============================================
# OUTPUT STRUCTURED DATA FOR pf_monitor.sh
# ============================================
# pf_monitor.sh greps for these exact prefixes
my $stats_json = encode_json( \%stats );
print "STATS_JSON:$stats_json\n";

my $warnings_json = encode_json( \@warnings );
print "WARNINGS_JSON:$warnings_json\n";

log_msg("=== pf_validator.pl complete ===");
exit 0;
