daemonize: true
pcap_interface: %%EXT_IF%%
promisc: true
debug: false

pidfile: /var/www/htdocs/tn/data/run/pmacct/pmacct-ext_if_json_mfs.pid
imt_path: /var/www/htdocs/tn/data/tmp/pmacct/pmacct-ext_if_json_mfs.imt

plugins: print[jsonpipe]
aggregate[jsonpipe]: src_host, dst_host, src_port, dst_port, proto, tcpflags, tos
print_output_file[jsonpipe]: /var/www/htdocs/tn/data/pipes/pmacct/ext_if_json.log
print_output[jsonpipe]: json
plugin_pipe_size: 4194304
print_refresh_time[jsonpipe]: 10
print_output_file_append: true
print_history[jsonpipe]: 15m
print_cache_entries[jsonpipe]: 8192
