daemonize: true
pidfile: /var/www/htdocs/tn/data/run/pmacct/pmacct-ext_if_json_log.pid
imt_path: /var/www/htdocs/tn/data/tmp/pmacct/pmacct-ext_if.imt
plugin_pipe_size: 1048576
pcap_interface: %%EXT_IF%%
snaplen: 1500
promisc: true
debug: false

plugins: print[jsonlog]

aggregate[jsonlog]: src_host, dst_host, src_port, dst_port, proto, tcpflags, tos
print_output_file[jsonlog]: /var/www/htdocs/tn/data/network/pmacct/ext/ext_if-%Y%m%d-%H%M.json
print_output[jsonlog]: json
print_refresh_time[jsonlog]: 60
print_output_file_append: true
print_history[jsonlog]: 15m
print_cache_entries[jsonlog]: 8192
