daemonize: true
pidfile: /var/www/htdocs/tn/data/run/pmacct/pmacct-int_if_json_mfs.pid
imt_path: /var/www/htdocs/tn/data/tmp/pmacct/pmacct-int_if_json_mfs.imt
pcap_interface: %%INT_IF%%
snaplen: 1500
promisc: true
debug: false

plugins: print[jsonpipe]
aggregate[jsonpipe]: src_host, src_mac, src_port, dst_host, proto
print_output_file[jsonpipe]: /var/www/htdocs/tn/data/pipes/pmacct/int_if_json.log
print_output[jsonpipe]: json
plugin_pipe_size: 4194304
print_refresh_time[jsonpipe]: 10
print_output_file_append: true
print_history[jsonpipe]: 15m
print_cache_entries[jsonpipe]: 8192
