CACert /usr/local/etc/sslproxy/ca.crt
CAKey /usr/local/etc/sslproxy/ca.key
Ciphers ALL:!RC4
LeafKeyRSABits 2048
User _sslproxy
Group _sslproxy
PidFile /var/www/htdocs/tn/data/run/sslproxy/sslproxy.pid
ConnectLog /var/www/htdocs/tn/data/logs/sslproxy/sslproxy_connect.log
Daemon yes
ConnIdleTimeout 120
ExpiredConnCheckPeriod 10
LogStats yes
StatsPeriod 1
RemoveHTTPAcceptEncoding no
RemoveHTTPReferer yes
VerifyPeer yes
AllowWrongHost no
UserAuth no
ValidateProto yes
MaxHTTPHeaderSize 8192
OpenFilesLimit 8192
ProxySpec http    127.0.0.1 8081 up:8080
ProxySpec http    ::1       8081 up:8080
ProxySpec https   127.0.0.1 8443 up:8080
ProxySpec https   ::1       8443 up:8080
ProxySpec pop3    127.0.0.1 8994 up:8110
ProxySpec pop3    ::1       8994 up:8110
ProxySpec pop3s   127.0.0.1 8995 up:8110
ProxySpec pop3s   ::1       8995 up:8110
ProxySpec pop3s   127.0.0.1 8993 up:8110
ProxySpec pop3s   ::1       8993 up:8110
ProxySpec smtp    127.0.0.1 8464 up:9199
ProxySpec smtp    ::1       8464 up:9199
ProxySpec smtps   127.0.0.1 8465 up:9199
ProxySpec smtps   ::1       8465 up:9199
ProxySpec autossl 127.0.0.1 8466 up:9199
ProxySpec autossl ::1       8466 up:9199
