pidfile = /var/www/htdocs/tn/data/run/p3scan/p3scan.pid
user = _p3scan
notifydir = /var/www/htdocs/tn/data/spool/p3scan/notify
virusdir = /var/www/htdocs/tn/data/spool/p3scan
extra = root@localhost
bytesfree = 100000
scannertype = clamd
scanner = 127.0.0.1:3310
virusregexp = .*: (.*) FOUND
checkspam
spamcheck = /usr/local/bin/spamc
template = /etc/p3scan/p3scan.mail
subject = *****UTMFW Virus WARNING*****
footer = /usr/local/bin/clamdscan -V
