LogFile /var/www/htdocs/tn/data/logs/clamd/clamd.log
LogFileMaxSize 0
LogTime yes
LogClean yes
LogSyslog yes
LogVerbose yes
PidFile /var/www/htdocs/tn/data/run/clamav/clamd.pid
TemporaryDirectory /var/www/htdocs/tn/data/tmp/clamav
DatabaseDirectory /var/db/clamav
LocalSocket /var/www/htdocs/tn/data/tmp/clamav/clamd.socket
TCPSocket 3310
TCPAddr 127.0.0.1
TCPAddr ::1
SelfCheck 3600
User _clamav
MaxRecursion 10
