# /etc/collectd_rrd_map_override.pm
# AUTO-GENERATED by collectd_reconciler.pm on Wed Jun 10 07:40:20 2026
# DO NOT EDIT -- re-run collectd_reconciler.pm to regenerate

package collectd_rrd_map_override;

# Returns hashref: collectd_id => absolute_rrd_path
sub get_map {
    return {
        'tangent/disk-sd0/disk_octets' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/disk-sd0/disk_octets.rrd',
        'tangent/interface-%%INT_IF%%/if_errors' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/interface-%%INT_IF%%/if_errors.rrd',
        'tangent/interface-%%INT_IF%%/if_octets' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/interface-%%INT_IF%%/if_octets.rrd',
        'tangent/interface-%%INT_IF%%/if_packets' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/interface-%%INT_IF%%/if_packets.rrd',
        'tangent/interface-%%EXT_IF%%/if_errors' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/interface-%%EXT_IF%%/if_errors.rrd',
        'tangent/interface-%%EXT_IF%%/if_octets' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/interface-%%EXT_IF%%/if_octets.rrd',
        'tangent/interface-%%EXT_IF%%/if_packets' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/interface-%%EXT_IF%%/if_packets.rrd',
        'tangent/interface-%%INT_IF%%/if_errors' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/interface-%%INT_IF%%/if_errors.rrd',
        'tangent/interface-%%INT_IF%%/if_octets' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/interface-%%INT_IF%%/if_octets.rrd',
        'tangent/interface-%%INT_IF%%/if_packets' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/interface-%%INT_IF%%/if_packets.rrd',
        'tangent/interface-pflog1/if_errors' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/interface-pflog1/if_errors.rrd',
        'tangent/interface-pflog1/if_octets' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/interface-pflog1/if_octets.rrd',
        'tangent/interface-pflog1/if_packets' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/interface-pflog1/if_packets.rrd',
        'tangent/ping/ping-1.1.1.1' =>
          '/var/www/htdocs/tn/data/rrd/collectd/tangent/ping/ping-1.1.1.1.rrd',
        'tangent/ping/ping-%%WAN_GW4%%' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/ping/ping-%%WAN_GW4%%.rrd',
        'tangent/ping/ping_droprate-1.1.1.1' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/ping/ping_droprate-1.1.1.1.rrd',
        'tangent/ping/ping_droprate-%%WAN_GW4%%' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/ping/ping_droprate-%%WAN_GW4%%.rrd',
        'tangent/ping/ping_stddev-1.1.1.1' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/ping/ping_stddev-1.1.1.1.rrd',
        'tangent/ping/ping_stddev-%%WAN_GW4%%' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/ping/ping_stddev-%%WAN_GW4%%.rrd',
        'tangent/processes-clamd/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-clamd/ps_code.rrd',
        'tangent/processes-clamd/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-clamd/ps_count.rrd',
        'tangent/processes-clamd/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-clamd/ps_cputime.rrd',
        'tangent/processes-clamd/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-clamd/ps_data.rrd',
        'tangent/processes-clamd/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-clamd/ps_pagefaults.rrd',
        'tangent/processes-clamd/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-clamd/ps_rss.rrd',
        'tangent/processes-clamd/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-clamd/ps_stacksize.rrd',
        'tangent/processes-clamd/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-clamd/ps_vm.rrd',
        'tangent/processes-cron/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-cron/ps_code.rrd',
        'tangent/processes-cron/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-cron/ps_count.rrd',
        'tangent/processes-cron/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-cron/ps_cputime.rrd',
        'tangent/processes-cron/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-cron/ps_data.rrd',
        'tangent/processes-cron/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-cron/ps_pagefaults.rrd',
        'tangent/processes-cron/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-cron/ps_rss.rrd',
        'tangent/processes-cron/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-cron/ps_stacksize.rrd',
        'tangent/processes-cron/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-cron/ps_vm.rrd',
        'tangent/processes-dhcpd/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-dhcpd/ps_code.rrd',
        'tangent/processes-dhcpd/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-dhcpd/ps_count.rrd',
        'tangent/processes-dhcpd/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-dhcpd/ps_cputime.rrd',
        'tangent/processes-dhcpd/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-dhcpd/ps_data.rrd',
        'tangent/processes-dhcpd/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-dhcpd/ps_pagefaults.rrd',
        'tangent/processes-dhcpd/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-dhcpd/ps_rss.rrd',
        'tangent/processes-dhcpd/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-dhcpd/ps_stacksize.rrd',
        'tangent/processes-dhcpd/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-dhcpd/ps_vm.rrd',
        'tangent/processes-e2guardian/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-e2guardian/ps_code.rrd',
        'tangent/processes-e2guardian/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-e2guardian/ps_count.rrd',
        'tangent/processes-e2guardian/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-e2guardian/ps_cputime.rrd',
        'tangent/processes-e2guardian/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-e2guardian/ps_data.rrd',
        'tangent/processes-e2guardian/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-e2guardian/ps_pagefaults.rrd',
        'tangent/processes-e2guardian/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-e2guardian/ps_rss.rrd',
        'tangent/processes-e2guardian/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-e2guardian/ps_stacksize.rrd',
        'tangent/processes-e2guardian/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-e2guardian/ps_vm.rrd',
        'tangent/processes-freshclam/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-freshclam/ps_code.rrd',
        'tangent/processes-freshclam/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-freshclam/ps_count.rrd',
        'tangent/processes-freshclam/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-freshclam/ps_cputime.rrd',
        'tangent/processes-freshclam/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-freshclam/ps_data.rrd',
        'tangent/processes-freshclam/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-freshclam/ps_pagefaults.rrd',
        'tangent/processes-freshclam/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-freshclam/ps_rss.rrd',
        'tangent/processes-freshclam/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-freshclam/ps_stacksize.rrd',
        'tangent/processes-freshclam/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-freshclam/ps_vm.rrd',
        'tangent/processes-ftpproxy/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ftpproxy/ps_code.rrd',
        'tangent/processes-ftpproxy/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ftpproxy/ps_count.rrd',
        'tangent/processes-ftpproxy/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ftpproxy/ps_cputime.rrd',
        'tangent/processes-ftpproxy/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ftpproxy/ps_data.rrd',
        'tangent/processes-ftpproxy/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ftpproxy/ps_pagefaults.rrd',
        'tangent/processes-ftpproxy/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ftpproxy/ps_rss.rrd',
        'tangent/processes-ftpproxy/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ftpproxy/ps_stacksize.rrd',
        'tangent/processes-ftpproxy/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ftpproxy/ps_vm.rrd',
        'tangent/processes-httpd/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-httpd/ps_code.rrd',
        'tangent/processes-httpd/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-httpd/ps_count.rrd',
        'tangent/processes-httpd/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-httpd/ps_cputime.rrd',
        'tangent/processes-httpd/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-httpd/ps_data.rrd',
        'tangent/processes-httpd/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-httpd/ps_pagefaults.rrd',
        'tangent/processes-httpd/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-httpd/ps_rss.rrd',
        'tangent/processes-httpd/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-httpd/ps_stacksize.rrd',
        'tangent/processes-httpd/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-httpd/ps_vm.rrd',
        'tangent/processes-ntpd/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ntpd/ps_code.rrd',
        'tangent/processes-ntpd/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ntpd/ps_count.rrd',
        'tangent/processes-ntpd/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ntpd/ps_cputime.rrd',
        'tangent/processes-ntpd/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ntpd/ps_data.rrd',
        'tangent/processes-ntpd/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ntpd/ps_pagefaults.rrd',
        'tangent/processes-ntpd/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ntpd/ps_rss.rrd',
        'tangent/processes-ntpd/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ntpd/ps_stacksize.rrd',
        'tangent/processes-ntpd/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-ntpd/ps_vm.rrd',
        'tangent/processes-p3scan/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-p3scan/ps_code.rrd',
        'tangent/processes-p3scan/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-p3scan/ps_count.rrd',
        'tangent/processes-p3scan/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-p3scan/ps_cputime.rrd',
        'tangent/processes-p3scan/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-p3scan/ps_data.rrd',
        'tangent/processes-p3scan/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-p3scan/ps_pagefaults.rrd',
        'tangent/processes-p3scan/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-p3scan/ps_rss.rrd',
        'tangent/processes-p3scan/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-p3scan/ps_stacksize.rrd',
        'tangent/processes-p3scan/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-p3scan/ps_vm.rrd',
        'tangent/processes-pflogd/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pflogd/ps_code.rrd',
        'tangent/processes-pflogd/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pflogd/ps_count.rrd',
        'tangent/processes-pflogd/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pflogd/ps_cputime.rrd',
        'tangent/processes-pflogd/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pflogd/ps_data.rrd',
        'tangent/processes-pflogd/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pflogd/ps_pagefaults.rrd',
        'tangent/processes-pflogd/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pflogd/ps_rss.rrd',
        'tangent/processes-pflogd/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pflogd/ps_stacksize.rrd',
        'tangent/processes-pflogd/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pflogd/ps_vm.rrd',
        'tangent/processes-pmacctd/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pmacctd/ps_code.rrd',
        'tangent/processes-pmacctd/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pmacctd/ps_count.rrd',
        'tangent/processes-pmacctd/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pmacctd/ps_cputime.rrd',
        'tangent/processes-pmacctd/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pmacctd/ps_data.rrd',
        'tangent/processes-pmacctd/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pmacctd/ps_pagefaults.rrd',
        'tangent/processes-pmacctd/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pmacctd/ps_rss.rrd',
        'tangent/processes-pmacctd/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pmacctd/ps_stacksize.rrd',
        'tangent/processes-pmacctd/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-pmacctd/ps_vm.rrd',
        'tangent/processes-smtp-gated/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtp-gated/ps_code.rrd',
        'tangent/processes-smtp-gated/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtp-gated/ps_count.rrd',
        'tangent/processes-smtp-gated/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtp-gated/ps_cputime.rrd',
        'tangent/processes-smtp-gated/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtp-gated/ps_data.rrd',
        'tangent/processes-smtp-gated/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtp-gated/ps_pagefaults.rrd',
        'tangent/processes-smtp-gated/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtp-gated/ps_rss.rrd',
        'tangent/processes-smtp-gated/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtp-gated/ps_stacksize.rrd',
        'tangent/processes-smtp-gated/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtp-gated/ps_vm.rrd',
        'tangent/processes-smtpd/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtpd/ps_code.rrd',
        'tangent/processes-smtpd/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtpd/ps_count.rrd',
        'tangent/processes-smtpd/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtpd/ps_cputime.rrd',
        'tangent/processes-smtpd/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtpd/ps_data.rrd',
        'tangent/processes-smtpd/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtpd/ps_pagefaults.rrd',
        'tangent/processes-smtpd/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtpd/ps_rss.rrd',
        'tangent/processes-smtpd/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtpd/ps_stacksize.rrd',
        'tangent/processes-smtpd/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-smtpd/ps_vm.rrd',
        'tangent/processes-snort/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snort/ps_code.rrd',
        'tangent/processes-snort/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snort/ps_count.rrd',
        'tangent/processes-snort/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snort/ps_cputime.rrd',
        'tangent/processes-snort/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snort/ps_data.rrd',
        'tangent/processes-snort/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snort/ps_pagefaults.rrd',
        'tangent/processes-snort/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snort/ps_rss.rrd',
        'tangent/processes-snort/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snort/ps_stacksize.rrd',
        'tangent/processes-snort/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snort/ps_vm.rrd',
        'tangent/processes-snortsentry/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snortsentry/ps_code.rrd',
        'tangent/processes-snortsentry/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snortsentry/ps_count.rrd',
        'tangent/processes-snortsentry/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snortsentry/ps_cputime.rrd',
        'tangent/processes-snortsentry/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snortsentry/ps_data.rrd',
        'tangent/processes-snortsentry/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snortsentry/ps_pagefaults.rrd',
        'tangent/processes-snortsentry/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snortsentry/ps_rss.rrd',
        'tangent/processes-snortsentry/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snortsentry/ps_stacksize.rrd',
        'tangent/processes-snortsentry/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-snortsentry/ps_vm.rrd',
        'tangent/processes-sockd/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sockd/ps_code.rrd',
        'tangent/processes-sockd/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sockd/ps_count.rrd',
        'tangent/processes-sockd/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sockd/ps_cputime.rrd',
        'tangent/processes-sockd/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sockd/ps_data.rrd',
        'tangent/processes-sockd/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sockd/ps_pagefaults.rrd',
        'tangent/processes-sockd/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sockd/ps_rss.rrd',
        'tangent/processes-sockd/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sockd/ps_stacksize.rrd',
        'tangent/processes-sockd/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sockd/ps_vm.rrd',
        'tangent/processes-spamd/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-spamd/ps_code.rrd',
        'tangent/processes-spamd/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-spamd/ps_count.rrd',
        'tangent/processes-spamd/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-spamd/ps_cputime.rrd',
        'tangent/processes-spamd/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-spamd/ps_data.rrd',
        'tangent/processes-spamd/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-spamd/ps_pagefaults.rrd',
        'tangent/processes-spamd/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-spamd/ps_rss.rrd',
        'tangent/processes-spamd/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-spamd/ps_stacksize.rrd',
        'tangent/processes-spamd/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-spamd/ps_vm.rrd',
        'tangent/processes-sshd/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sshd/ps_code.rrd',
        'tangent/processes-sshd/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sshd/ps_count.rrd',
        'tangent/processes-sshd/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sshd/ps_cputime.rrd',
        'tangent/processes-sshd/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sshd/ps_data.rrd',
        'tangent/processes-sshd/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sshd/ps_pagefaults.rrd',
        'tangent/processes-sshd/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sshd/ps_rss.rrd',
        'tangent/processes-sshd/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sshd/ps_stacksize.rrd',
        'tangent/processes-sshd/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sshd/ps_vm.rrd',
        'tangent/processes-sslproxy/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sslproxy/ps_code.rrd',
        'tangent/processes-sslproxy/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sslproxy/ps_count.rrd',
        'tangent/processes-sslproxy/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sslproxy/ps_cputime.rrd',
        'tangent/processes-sslproxy/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sslproxy/ps_data.rrd',
        'tangent/processes-sslproxy/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sslproxy/ps_pagefaults.rrd',
        'tangent/processes-sslproxy/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sslproxy/ps_rss.rrd',
        'tangent/processes-sslproxy/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sslproxy/ps_stacksize.rrd',
        'tangent/processes-sslproxy/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-sslproxy/ps_vm.rrd',
        'tangent/processes-unbound/ps_code' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-unbound/ps_code.rrd',
        'tangent/processes-unbound/ps_count' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-unbound/ps_count.rrd',
        'tangent/processes-unbound/ps_cputime' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-unbound/ps_cputime.rrd',
        'tangent/processes-unbound/ps_data' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-unbound/ps_data.rrd',
        'tangent/processes-unbound/ps_pagefaults' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-unbound/ps_pagefaults.rrd',
        'tangent/processes-unbound/ps_rss' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-unbound/ps_rss.rrd',
        'tangent/processes-unbound/ps_stacksize' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-unbound/ps_stacksize.rrd',
        'tangent/processes-unbound/ps_vm' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/processes-unbound/ps_vm.rrd',
        'tangent/swap-dev_sd0b/swap-free' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/swap-dev_sd0b/swap-free.rrd',
        'tangent/swap-dev_sd0b/swap-used' =>
'/var/www/htdocs/tn/data/rrd/collectd/tangent/swap-dev_sd0b/swap-used.rrd',
    };
}

1;
