UpdateLogFile /var/www/htdocs/tn/data/logs/freshclam/freshclam.log
LogFileMaxSize 0
LogVerbose yes
LogSyslog yes
PidFile /var/www/htdocs/tn/data/run/clamav/freshclam.pid
DatabaseOwner _clamav
DatabaseMirror database.clamav.net
NotifyClamd /etc/clamd.conf
ConnectTimeout 60
