# $OpenBSD: unbound.conf,v 1.21 2020/10/28 11:35:58 sthen Exp $

server:
	interface: 127.0.0.1
	interface: ::1
	interface: %%INT_IP4%%         # IPv4 LAN
	interface: fd0a0a:0a00::1      # IPv6 LAN

	access-control: 0.0.0.0/0 refuse
        access-control: ::0/0 refuse
        
	access-control: 192.168.0.0/16 allow
	access-control: 172.16.0.0/12 allow
	access-control: 10.0.0.0/8 allow
	access-control: fe80::/10 allow
	access-control: fc00::/7 allow
	access-control: 127.0.0.0/8 allow
	access-control: ::1/128 allow	

	insecure-lan-zones: yes
	private-address: 10.0.0.0/8
	private-address: 172.16.0.0/12
	private-address: 192.168.0.0/16
	private-domain: localdomain

	do-ip6: yes
	prefer-ip6: no
	dns64-prefix: %%NAT64_PFX%%
        tcp-idle-timeout: 30000
	edns-tcp-keepalive: yes
	edns-tcp-keepalive-timeout: 30000
	use-syslog: yes
	log-queries: yes
	verbosity: 1
	hide-identity: yes
	hide-version: yes
	qname-minimisation: yes
	#auto-trust-anchor-file: "/var/unbound/etc/root.key"
	tls-cert-bundle: "/etc/ssl/cert.pem"
	val-log-level: 2
	aggressive-nsec: yes

	# Cache settings
	cache-max-ttl: 604800
	cache-min-ttl: 1800
	infra-cache-numhosts: 100000
	infra-cache-slabs: 4
	key-cache-slabs: 4
	msg-cache-size: 128m
	msg-cache-slabs: 4
	rrset-cache-size: 256m
	rrset-cache-slabs: 4

	# Performance
	num-threads: 1
	prefetch: yes
	prefetch-key: yes
	so-sndbuf: 0
	so-rcvbuf: 0
	so-reuseport: yes

module-config: "dns64 iterator"

remote-control:
	control-enable: yes
	control-interface: /var/run/unbound.sock

forward-zone:
	name: "."
	forward-ssl-upstream: yes
        forward-first: no

    	# Cloudflare DNS over TLS
	#forward-addr: 1.1.1.1@853#cloudflare-dns.com
	#forward-addr: 1.0.0.1@853#cloudflare-dns.com

    	# Google Public DNS over TLS
    	#forward-addr: 8.8.8.8@853#dns.google
    	#forward-addr: 8.8.4.4@853#dns.google

	# forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
	# forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com
	# forward-addr: 2001:4860:4860::8888@853#dns.google
	# forward-addr: 2001:4860:4860::8844@853#dns.google
	
	# 9.9.9.9 - Threat-blocking with DNSSEC
	# forward-addr: 2620:fe::fe@853#dns.quad9.net
	# forward-addr: 2620:fe::9@853#dns.quad9.net

	# 9.9.9.9 - Threat-blocking with DNSSEC
        # forward-addr: 9.9.9.9@853#dns.quad9.net
        # forward-addr: 149.112.112.112@853#dns.quad9.net

	# 9.9.9.11 - Threat blocking, DNSSEC, and ECS
        # forward-addr: 9.9.9.11@853#dns11.quad9.net
	# forward-addr: 149.112.112.11@853#dns11.quad9.net

	# 9.9.9.10 - No threat blocking, no DNSSEC
	# forward-addr: 9.9.9.10@853#dns10.quad9.net
        # forward-addr: 149.112.112.10@853#dns10.quad9.net


	# 9.9.9.11 - Threat blocking, DNSSEC, and ECS
         forward-addr: 9.9.9.11@853#dns11.quad9.net
         forward-addr: 149.112.112.11@853#dns11.quad9.net
	 
	# Fallback
	 forward-addr: 1.1.1.1@853#cloudflare-dns.com
	 forward-addr: 1.0.0.1@853#cloudflare-dns.com


	# 9.9.9.11 - Threat blocking, DNSSEC, and ECS
	 forward-addr: 2620:fe::11@853#dns11.quad9.net
	 forward-addr: 2620:fe::fe:11@853#dns11.quad9.net
	
	# Fallback
	 forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
         forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com

